/**
 * "A word from the artist" — Ritushka's own letter, in English and Hungarian.
 *
 * IMPORTANT: this is the artist's own voice, verbatim. The only editorial
 * changes made to either version are paragraph breaks, punctuation and
 * (in the Hungarian) restored diacritics — the source file was typed
 * without accents. Do NOT soften, tidy or "professionalise" the wording.
 *
 * Both arrays are paragraph-for-paragraph aligned, so the language toggle
 * can swap them in place. Keep them the same length.
 *
 * Sources: /About page/A word fron the artist.txt
 *          /About page/The Hungarian People.txt
 */

export const letterEn: string[] = [
  'Drawing from the depths of my memory, my career as an artist reaches all the way back to when I was four. I grew up in communist Hungary, in one of Budapest’s outer districts — Pesterzsébet, to be exact — in the middle of a concrete jungle, right next to lovely Csepel, which was maybe an even bigger dump than our own housing estate. A gold mine for proles and working stiffs; to us it was a wonderland, since we had no idea anything else existed. For a car or a landline you had to sit patiently on a waiting list for decades. The everyday view was rows of ten-story blocks lined up in parallel, inside which thousands of families merrily lived out their lives in tiny flats. Stimulation, inspiration, visual experience: zero.',

  'I was one of the lucky ones, as I went to the famous purple kindergarten — the most colourful building in the whole district. That’s the source of my first memory, the one that left huge question marks in everyone’s mind. Day after day I just sat at the drawing table and daubed away. Every day I came home with the same masterpiece: a whale surfacing from the depths of the sea, cheerfully spraying a jet of water into the air. I hauled whales home by the ton… to the great astonishment of my kindergarten teacher and my parents, since I had never in my life laid eyes on a whale. Beyond Hungary’s great rivers and lakes, a puddle at most. A sea — or God forbid an ocean — not even in a picture. The origin of that inspiration is a mystery to this day. Drawing became the muse of my early childhood.',

  'Entering into the wonderous school life journey, I spent my summers under my grandparents’ wings, watching their deft, industrious hands. My grandfather made oil paintings of professional quality. My grandmothers conjured up breathtaking handiwork — crochet, knitting, embroidered pictures. My great-grandfather built a miniature working steam locomotive out of ‘nothing’. It tantalised me. Something exciting was always taking shape in their hands, and their urge to create ran through our days with untiring force. I was infected for life.',

  'As the years went by and my brain cells multiplied, I learned, mastered, and picked up everything from them just by watching, and — setting all modesty aside — became a mini creator. At first my art-making was just something to kill the boredom in our limited, simple lives, but soon I grasped the essence of it. Creating is a wonder. I was unstoppable: I crocheted, knitted, embroidered, sewed, painted furniture, carved, sculpted with clay until I dropped.',

  'Then one day it simply passed. But it didn’t leave a void behind — it struck a spark of room for the great love. From three-dimensional creations back to good old drawing. I managed to untangle myself from the thicket of yarns and stubby little needles and got out paper, coloured pencils and ink again. The great boredom-killing impulse was over and the era of nonstop gift-making began. I planned out my creations deliberately, and within moments I’d flooded every last wall of our tiny flat with my artworks. By Easter I was already waiting for Christmas — not to receive anything, but so I could hand over my daubings with a great fanfare. With my silly teenage-girl brain I worked out that the result is far more successful and effective if I sniff out where a bit more TLC is needed, and then designed and dreamed up what I’d create accordingly. That, I think, is where my interior-design streak began to flourish.',

  'As a young teen I went through the ‘Nunuke’, the “little dudes” phase — teeny-weeny imaginary little clumsy critters with all sorts of chirpers, antennae, huge bulging, goggling eyes and loads of personality. Then, as my hormones kicked in and pushed me into more of a girly phase, my attention drifted from the little gnomes to the more eye-catching members of the opposite sex. I went through an interesting change of style. I drew enormous inspiration from my idol, the man himself, Salvador Dalí. Everything twisted, writhed, seduced, drove you wild, radiated lust out of my surrealist, sexy, provocative picture series. The two styles, the two mediums, are as different as heaven and earth: the technique, the execution, the message, the content, the palette. Surprisingly, both are a satisfyingly creative and a visual experience on every level.',

  'While my fledgling works were decorating my mum’s flat, I obviously couldn’t sit still on my butt. I took off into the wide world. I travelled all over Europe, lived and worked in America, then my heart pulled me back to Budapest and I completed an interior design degree — but I ended up in Australia. The usual story: we came for one year, with two suitcases, zero dough, plenty of ambition and drive, hungry for experiences. That was 26 years ago.',

  'Circumstances once again knocked me off the path of letting my creative streak unfold — until one fine day, egged on by a couple of gin and tonics, I very cleverly spent that week’s carefully saved rent money on canvas, brushes and paint. My two successful styles entered a blessed marriage, and I started making personalized, insanely colourful, meticulously detailed paintings for children, full of life, love and joy. My little pieces found huge success and an audience at lightning speed, my own little business took off. I loved it. They loved it. I loved that they loved it. Alongside my full-time job I worked on commissions through the night, and by now hundreds of families across three continents own a piece of my little dream world.',

  'Meanwhile my own dream world had of course grown by two fluffy heads, but my urge to create didn’t let up. I figured I’d have a go at painting even with an enormous belly — and successfully, too: the Hunters Hill Art Exhibition accepted one of my works for the show. I could feel that the devil still wasn’t resting, that something else wanted to burst out… so I went exploring a multitude of channels to let the beast out of the bag. I made up my mind and signed up for two courses at Willoughby Art School, for a bit of a tickle. To shore up my weak spot at the time, I learned to draw all over again, specifically to refine portraits and various forms of madness — nudes, for instance. Ending up under Richard Byrne’s wing, I adored his classes: not just the life drawing, the making of art, but his dry English humour as well! It did a world of good not only for my outlook but for the upkeep of my abs. What a legend!',

  'Alongside all this creative artistry, I took up one more piece of foolishness. I figured I ought to have a taste of this abstract thingy too — I’d never had a bloody go at anything like it before anyway. Big mistake. How do I put this… I think every parent has committed this particular crime against their child: putting a slice of lemon into the little hand and saying with a smile, here you go, it’s yummy! The little one’s face screws right up as they lick it, their eyes go wide, and a bewilderment settles over their face like nothing before. At first it’s unpleasant, but for some strange reason you enjoy it anyway — you’re drooling while you’re grimacing. The more times you taste it, the more it dawns on you that this is something divine. When my first two abstract paintings were born, I went from a sour, distasteful grimace to heavenly adoration and fulfilment. Hallelujah. I’ve found you at last, you’ve found me at last — where have you been all this time, abstract? I’m not letting you go now. We’ve fallen far too hard for each other, head over hills. Let’s make each other complete, discover every tiny and gigantic detail of one another, in every satisfying form of meticulousness and nuance. Forever and ever. We are living happily ever after.',
];

export const letterHu: string[] = [
  'Művésznői pályafutásom, emlékeim bugyrából merítve, egészen 4 éves koromig nyúlik vissza. Kommunista Magyarországon, Budapest külkerületében — konkrétan Pesterzsébeten —, a betonrengeteg közepén nőttem fel, a vonzó Csepel szomszédságában, ami talán még a mi lakótelepünknél is pocsékabb volt. A prolik és a munkik aranybányája, nekünk csodaország, hiszen fogalmunk sem volt, hogy létezik akármi más. Autóra és vonalas telefonra évtizedekig kellett várólistán türelmesen csücsülni. A tízemeletes házak párhuzamos tömege volt mindennapjaink látványa, amikben családok ezrei pirinyó lakásokban vígan élték mindennapjaikat. Stimuláció, inspiráció, vizuális élmény nulla.',

  'Én szerencsés voltam, mert a híres lila óvodába jártam, ami a legszínesebb épület volt az egész kerületben. Innen ered első emlékem, ami mindenki fejében hatalmas kérdőjeleket szült. Nap mint nap csak ültem a rajzolóasztal mellett és pingáltam. Minden nap ugyanazzal a remekművel tértem haza: egy bálna bukkan fel a tenger mélyéről, vidáman vízsugarat spriccelve a magasba. Tonnaszámra hordtam haza a bálnákat… Az óvónénim és szüleim legnagyobb meglepetésére, hiszen soha életemben nem láthattam bálnát. A nagy magyar folyókon és tavakon kívül legfeljebb pocsolyát. Tengert vagy ne adj Isten óceánt még képen sem. Ihletem kiindulópontja mai napig rejtély. Rajzolás gyerekkorom múzsája.',

  'Jártuk az országot, és a nyarakat nagyszüleim szárnyai alatt töltöttem. Ügyes, szorgos kezeiket figyeltem. Nagypapám profi olajfestményeket alkotott, nagymamáim lélegzetelállító kézimunkákat, horgolásokat, kötéseket és hímzett képeket varázsoltak, dédnagypapám miniatűr működő gőzmozdonyt épített a ‚semmiből’. Mindig valami izgalmas kerekedett ki kezeikből és alkotóvágyuk lankadatlan erővel kísérte mindennapjainkat. Meg lettem mérgezve.',

  'Évek múlásával és agysejtjeim szaporodásával megtanultam, kitanultam, ellestem mindent tőlük és minden szerénységet félretéve mini kreátorka lettem. Művészkedésem először unaloműző kellék lett limitált, egyszerű életünkben, de hamarosan rájöttem a lényegre. Alkotni csoda. Megállíthatatlan voltam, horgoltam, kötöttem, hímeztem, varrtam, bútorokat pingáltam, faragtam, gyurmáztam kifulladásig.',

  'Aztán egyszer csak elmúlt. De nem űrt hagyott maga után, hanem helyet csiholt a nagy szerelemnek. 3 dimenziós alkotástól vissza a hagyományos rajzokhoz. Sikerült kibogoznom magam a fonalak és a kurta-furcsa tűk rengetegéből és ismét papírt, színes ceruzát, tintát vettem elő. Elmúlt a nagy unaloműző indíttatás és elkezdődött a folyamatos ajándékkészítések időszaka. Tudatosan tervezgettem kreálmányaimat és pillanatok alatt elárasztottam pirinyó lakásunk összes létező falát a műalkotásaimmal. Már húsvétkor a karácsonyt vártam, nem azért, hogy kapjak, hanem hogy nagy csinnadrattával átadhassam a pingálásaimat. Kiokoskodtam kis csitri agyammal, hogy sokkal sikeresebb és hatásosabb az eredmény, ha kiszimatolom hova kell még egy kis TLC, úgy terveztem és álmodtam meg mit is fogok kreálni. Innen ered lakberendezői és design vénám… úgy gondolom.',

  'Kis tiniként átestem a ‚Nunuke’, ‚kis bigyókák’ korszakon, akik irinyó-pirinyó kis képzeletbeli élőlénykék mindenféle csipogókkal, csápokkal, hatalmas gülü szemekkel és rengeteg personával. Ahogy beütött hormonháztartásom inkább a kis nőcis időszakba és figyelmem a manócskákról a másik nem szembetűnőbb tagjaira esett, érdekes stílusváltáson estem keresztül. Hatalmas inspirációt merítettem példaképemtől, az embertől, magától Salvador Dalítól. Minden tekergett, vonaglott, csábított, vadított, buján sugárzott a non figuratív, szexi, izgató képsorozataimból. A két stílus, médium ég és föld ellentéte: a technika, a kivitelezés, a mondanivaló, a tartalom, a színvilág. Meglepő módon minden szinten kielégítő alkotói és vizuális élmény.',

  'Amíg szárnyaimat bontogató alkotásaim anyukámék lakását díszítették, persze én nem tudtam a seggemen ülni. Nyakamba vettem a nagyvilágot. Bejártam Európát, majd Amerikában éltem és dolgoztam, majd szívem visszahúzott Budapestre és lakberendezői iskolát végeztem, de végül Ausztráliában kötöttem ki. Szokásos sztori, egy évre jöttünk, két bőrönddel, zéró zsozsóval, rengeteg ambícióval és szorgalommal, élményekre éhesen. Ez 26 éve történt.',

  'A körülmények ismét elkanyarítottak alkotói vénám kibontakozásától, amíg egy szép napon pár pohárka gin and tonic biztatására a heti kispórolt lakbéremet nagy okosan vászonra, ecsetre és festékre költöttem. Két sikeres stílusom áldásos házasságot kötött és elkezdtem személyre szabott, élettel, szeretettel, vidámsággal teli, irtó színes, aprólékos festményeket készíteni gyerekeknek. Szösszeneteim villámgyorsan hatalmas sikerre és nézőközönségre találtak és beindult a saját kis bizniszem. Imádtam. Imádták. Imádtam, hogy imádták. Főmunkaidős állásom mellett éjjeleken át a megrendeléseimen dolgoztam és mára már 3 kontinensen családok százainak van egy kis darabkája az én kis álomvilágomból.',

  'Közben persze az én álomvilágom is gyarapodott két pelyhes fejűvel, de alkotásvágyam nem csillapodott. Gondoltam, még hatalmas pocakkal is megpróbálkozok kreálni — és eredményesen: a Hunters Hill Art Exhibition elfogadta az egyik művemet kiállításra. Éreztem, hogy az ördög még mindig nem nyugszik, valami még ki akar buggyanni… kerestem, hogy melyik csatornán esedékes ez a történelmi esemény. Gondoltam egyet és beiratkoztam a Willoughby Art School két tanfolyamára is egy kis csikizésre. Ekkori gyenge pontom erősítése céljából rajzolni tanultam ismét, kifejezetten a portrék és különbféle eszeveszettségek finomítására, mint például a pucérkodás. Richard Byrne szárnyai alá kerülve imádtam az óráit és nem csak a pucérkodást, alkotást, hanem a száraz, angol humorát is! Kifejezetten jót tett nem csak a világlátásomnak, hanem a hasizmaim karbantartására is. What a legend!',

  'E mellett a szórakoztató iparág mellett még egy bolondságra adtam a fejem. Gondoltam, ezt az absztrakt micsodát is meg kellene kóstolnom, olyat meg úgysem fingottam. Nagy hiba volt. Hogy is mondjam… szerintem minden szülő elkövette ezt a bűncselekményt a gyerekével, citromkarikát adni a kis kezecskébe és mosolyogva mondani, hogy tessék, nagyon finom! A babóca arca akkorát facsarodik, ahogy benyalja, a szeme kikerekedik és értetlenség ül ki az arcára, mint még soha. Először kellemetlen, de valami furcsa okból kifolyólag mégis élvezed, csurog a nyálad miközben fancsalogsz. Minél többször megkóstolod, annál jobban tudatosul benned, hogy ez valami isteni. Első két absztrakt festményem születésekor fanyalgással teli fintorgáson keresztül mennyei imádat és kielégültség töltött el. Hallelujah. Végre megtaláltalak, végre megtaláltál engem, hol voltál eddig absztrakt? Most már el nem engedlek, hisz mi már túlságosan egymásba zúgtunk. Boldogítsuk egymást és fedezzük fel minden apró és minden gigantikus részletünket az aprólékosság és a felületesség minden kielégítő formájában. Mindörökké, ámen.',
];

/** Sanity guard — the two languages must stay paragraph-aligned. */
export const letterParagraphCount = letterEn.length;
