"""Assigns each artwork to the interior scene that suits it best, then rewrites
src/data/mockups.ts.

Deterministic: the same inputs always give the same assignment, so mockup URLs are
stable and nothing churns when an unrelated artwork is added. No API calls, no
randomness — just scoring.

Run:  python3 scripts/match-scenes.py
"""
from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mockup_engine import choose_placement  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

SCENES_JSON = 'mockups/scenes.json'

WARM = {'rose', 'coral', 'flame', 'orange', 'crimson', 'gold', 'blush', 'apricot',
        'butter', 'umber', 'russet', 'scarlet', 'red', 'terracotta', 'peach', 'pink'}
COOL = {'blue', 'teal', 'aqua', 'turquoise', 'cobalt', 'ultramarine', 'sea', 'mist',
        'ice', 'jade', 'slate', 'seafoam', 'ocean', 'lagoon', 'sky'}
NEUTRAL = {'white', 'bone', 'sand', 'stone', 'grey', 'gray', 'cream', 'oyster', 'chalk',
           'taupe', 'pearl', 'silver', 'black', 'dune', 'ochre', 'brown', 'earth'}


def load_ts_array(path):
    src = open(path, encoding='utf-8').read()
    return json.loads(src[src.index('= [') + 2: src.rindex(']') + 1])


def write_ts(path, name, type_name, data):
    banner = '// AUTO-GENERATED by scripts/match-scenes.py — edit mockups/scenes.json instead.\n'
    body = json.dumps(data, indent=2, ensure_ascii=False)
    open(path, 'w', encoding='utf-8').write(
        f"{banner}import type {{ {type_name} }} from './types';\n"
        f"export const {name}: {type_name}[] = {body};\n")


def palette_temp(palette: str) -> str:
    """warm / cool / neutral / vivid, from the curated palette description."""
    words = set(re.findall(r'[a-z]+', palette.lower()))
    w, c, n = len(words & WARM), len(words & COOL), len(words & NEUTRAL)
    if w and c and max(w, c) >= 2:
        return 'vivid'
    if w > c and w >= n:
        return 'warm'
    if c > w and c >= n:
        return 'cool'
    if n >= max(w, c):
        return 'neutral'
    return 'vivid'


def score(art, scene, used: dict) -> float | None:
    """Higher is better. None means the work physically does not belong on that wall."""
    h, w = art['heightCm'], art['widthCm']
    if not h or not w:
        return None
    # Allow for the frame, which the compositor adds around the canvas.
    place = choose_placement(scene, w + 5, h + 5)
    if place is None:
        return None            # no position in this room has the clearance for it
    u = place

    m = scene.get('match', {})
    s = 0.0

    if art['orientation'] in m.get('orientations', []):
        s += 4.0
    if palette_temp(art['palette']) in m.get('palettes', []):
        s += 3.0
    if art['primaryCollection'] in m.get('styles', []):
        s += 3.0

    # A work should feel deliberate on the wall: neither lost nor wedged in.
    sweet = u.get('maxWidthCm', 200) * 0.62
    s += 2.0 * max(0.0, 1.0 - abs(w - sweet) / sweet)
    if w < u.get('minWidthCm', 0):
        s -= 2.5

    # Spread the collection across the library rather than stacking one room.
    s -= 1.4 * used.get(scene['id'], 0)
    return s


def main():
    if not os.path.exists(SCENES_JSON):
        sys.exit(f"No {SCENES_JSON} yet — add master interiors first (see mockups/README.md).")

    from PIL import Image
    scenes = json.load(open(SCENES_JSON, encoding='utf-8'))['scenes']
    for sc in scenes:                       # each scene keeps its own framing
        with Image.open(os.path.join('mockups/scenes', sc['file'])) as im:
            sc['_aspect'] = f'{im.width} / {im.height}'
    artworks = load_ts_array('src/data/artworks.ts')
    previous = {m['artworkSlug']: m for m in load_ts_array('src/data/mockups.ts')}
    old = {k: v['slug'] for k, v in previous.items()}

    # Largest works first: they have the fewest walls that can take them.
    ordered = sorted(artworks,
                     key=lambda a: (-(a['heightCm'] or 0) * (a['widthCm'] or 0), a['slug']))

    used: dict = {}
    assigned = {}
    unplaced = []
    for a in ordered:
        ranked = []
        for sc in scenes:
            v = score(a, sc, used)
            if v is not None:
                ranked.append((v, sc['id'], sc))
        if not ranked:
            unplaced.append(a['slug'])
            continue
        ranked.sort(key=lambda t: (-t[0], t[1]))       # score desc, then id for stability
        best = ranked[0][2]
        assigned[a['slug']] = best
        used[best['id']] = used.get(best['id'], 0) + 1

    mockups = []
    redirects = {}
    by_slug = {a['slug']: a for a in artworks}
    for i, a in enumerate(sorted(artworks, key=lambda x: x['slug'])):
        sc = assigned.get(a['slug'])
        if not sc:
            # No calibrated wall suits this work yet — keep whatever it already had
            # rather than leaving the artwork page without an in-situ view.
            keep = previous.get(a['slug'])
            if keep:
                keep['id'] = 'mk-' + str(len(mockups) + 1).zfill(3)
                keep.setdefault('aspect', '4 / 3')
                mockups.append(keep)
            continue
        slug = f"{a['slug']}-in-{sc['id']}"
        size = (f"{a['heightCm']} × {a['widthCm']} cm"
                if a['heightCm'] and a['widthCm'] else None)
        room = sc.get('room', sc['name'])
        mockups.append({
            'id': 'mk-' + str(len(mockups) + 1).zfill(3),
            'slug': slug,
            'sceneId': sc['id'],
            'room': room,
            'artworkSlug': a['slug'],
            'title': f"{a['title']} in a {room.lower()}",
            'image': f'/mockups/{slug}.jpg',
            'alt': (f"{a['title']} by Ritushka hanging in a {room.lower()}"
                    + (f", shown to scale at {size}" if size else '')),
            'seoTitle': f"{a['title']} in a {room} | Ritushka",
            'metaDescription': (
                f"See {a['title']}" + (f" ({size})" if size else '')
                + f" by Ritushka hanging in a {room.lower()}, composited at true physical "
                  "scale. Placement and proportion reference for collectors and interior "
                  "designers. Enquire to acquire or commission."),
            'credit': sc.get('credit'),
            'aspect': sc['_aspect'],
        })
        prev = old.get(a['slug'])
        if prev and prev != slug:
            redirects[prev] = slug

    write_ts('src/data/mockups.ts', 'mockups', 'Mockup', mockups)

    # Keep artwork -> mockup links in step
    art_src = load_ts_array('src/data/artworks.ts')
    for a in art_src:
        a['mockups'] = [m['slug'] for m in mockups if m['artworkSlug'] == a['slug']]
    write_ts('src/data/artworks.ts', 'artworks', 'Artwork', art_src)

    json.dump(redirects, open('mockups/redirects.json', 'w', encoding='utf-8'),
              indent=1, sort_keys=True)

    composited = sum(1 for m in mockups if m.get('sceneId') in {s['id'] for s in scenes})
    print(f"scenes {len(scenes)} | artworks {len(artworks)} | mockups {len(mockups)} "
          f"| photographic {composited} | kept on the old renderer {len(mockups) - composited}")
    for sc in scenes:
        print(f"   {sc['id']:28s} {used.get(sc['id'], 0)} works")
    if unplaced:
        print('!! no wall large enough for:', ', '.join(unplaced))
    if redirects:
        print(f"{len(redirects)} mockup URLs changed — added to mockups/redirects.json")


if __name__ == '__main__':
    main()
