"""Syncs the site data from the Artwork Register spreadsheet.

Source of truth: "Artwork Records.ods" -> sheet "Artwork Register".
Reads the register, matches each row to the existing artwork entry, and rewrites
src/data/artworks.ts and src/data/mockups.ts with the real recorded values
(dimensions, depth, orientation, framing, description, sold status).

Curated editorial fields (palette, collections, subject line) are preserved.
Nothing is invented: columns left blank in the register stay blank on the site.

Re-run after editing the spreadsheet:  python3 scripts/sync-register.py
"""
import json, os, re, difflib, sys
import pandas as pd

REGISTER = 'Artwork Records.ods'
SHEET = 'Artwork Register'

# Register spellings that supersede the earlier working titles, with the
# typography we want on the site.
TITLE_OVERRIDES = {
    'eruption': 'Eruption',
    'marshmallow': 'Marshmallow',
    'peace-of-white-heaven': 'Peace of White Heaven',
    'tree-of-our-lives': 'Tree of Our Lives',
}
# Old slug -> new slug, for asset renames and 301 redirects.
SLUG_CORRECTIONS = {
    'erruption': 'eruption',
    'mashmellow': 'marshmallow',
    'piece-of-white-heavan': 'peace-of-white-heaven',
    'tree-of-our-life': 'tree-of-our-lives',
}


def norm(s):
    s = re.sub(r'[^a-z0-9]', '', str(s).lower())
    # "The World In My Eyes II" and "... 2" are the same painting
    return re.sub(r'ii$', '2', s)


def slugify(s):
    s = str(s).strip().lower()
    s = s.replace('&', ' and ')
    s = re.sub(r'[^a-z0-9]+', '-', s)
    return s.strip('-')


def cell(row, hdr, name):
    """Value for a named column, or None when blank."""
    if name not in hdr:
        return None
    v = row[hdr.index(name)]
    if v is None:
        return None
    s = str(v).strip()
    if s == '' or s.lower() == 'nan':
        return None
    return v


def num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def trim_cm(x):
    """900.0 -> 90, 91.0 -> 91, 76.5 -> 76.5"""
    return int(x) if abs(x - round(x)) < 1e-9 else round(x, 1)


def read_register(path=REGISTER):
    df = pd.read_excel(path, sheet_name=SHEET, header=None, engine='odf')
    hdr = [str(v).strip() for v in df.iloc[1].tolist()]
    out = []
    for i in range(2, df.shape[0]):
        row = df.iloc[i].tolist()
        title = cell(row, hdr, 'Title')
        if not title:
            continue
        h_mm = num(cell(row, hdr, 'Height (mm)'))
        w_mm = num(cell(row, hdr, 'Width (mm)'))
        # The "Sold" column is the primary marker, but it is not always kept up to
        # date — a recorded Sale Price or Date Sold is equally conclusive. The
        # "Status" column still holds values from the template's sample rows, so it
        # is deliberately ignored.
        sold_flag = cell(row, hdr, 'Sold')
        sold = (str(sold_flag).strip().lower() == 'sold'
                or bool(str(cell(row, hdr, 'Sale Price') or '').strip())
                or bool(str(cell(row, hdr, 'Date Sold') or '').strip()))
        out.append({
            'inventoryId': cell(row, hdr, 'Inventory ID'),
            'title': ' '.join(str(title).split()),
            'description': (str(cell(row, hdr, 'Description') or '').strip() or None),
            'inspiration': (str(cell(row, hdr, 'Inspiration / Location') or '').strip() or None),
            'orientation': (str(cell(row, hdr, 'Orientation') or '').strip().lower() or None),
            'heightCm': trim_cm(h_mm / 10) if h_mm else None,
            'widthCm': trim_cm(w_mm / 10) if w_mm else None,
            'depthCm': num(cell(row, hdr, 'Depth (cm)')),
            'framed': str(cell(row, hdr, 'Framed?') or '').strip().lower() == 'yes',
            'frameDescription': (str(cell(row, hdr, 'Frame Description') or '').strip() or None),
            'edition': (str(cell(row, hdr, 'Edition Type') or '').strip() or None),
            'sold': sold,
            # Published retail price. Written by scripts/apply-pricing-model.py from
            # pricing.config.json — the register stays the single source of truth.
            'price': num(cell(row, hdr, 'List Price')),
            'currency': (str(cell(row, hdr, 'Currency') or '').strip() or 'AUD'),
        })
    return out


def load_ts_array(path):
    src = open(path, encoding='utf-8').read()
    return json.loads(src[src.index('= [') + 2: src.rindex(']') + 1])


def write_ts(path, name, type_name, data):
    banner = '// AUTO-GENERATED by scripts/sync-register.py from "Artwork Records.ods".\n'
    body = json.dumps(data, indent=2, ensure_ascii=False)
    open(path, 'w', encoding='utf-8').write(
        f"{banner}import type {{ {type_name} }} from './types';\n"
        f"export const {name}: {type_name}[] = {body};\n")


def inches(cm):
    return round(cm / 2.54, 1)


def money(v, currency='AUD'):
    """5850 -> 'A$5,850'. Whole dollars only — the price list is rounded."""
    symbol = 'A$' if currency == 'AUD' else f'{currency} '
    return f"{symbol}{int(round(v)):,}"


def size_phrase(a):
    if a['heightCm'] is None or a['widthCm'] is None:
        return None
    return (f"{trim_cm(a['heightCm'])} × {trim_cm(a['widthCm'])} cm "
            f"({inches(a['heightCm']):g} × {inches(a['widthCm']):g} in)")


def build_story(a, subject):
    """Artist's own words first, then the studio/material context."""
    parts = []
    if a.get('description'):
        d = a['description'].strip()
        parts.append(d if d.endswith(('.', '!', '?', '—')) else d + '.')
    size = size_phrase(a)
    frame = a.get('frameDescription')
    sentence = (f"{a['title']} is an original painting by Ritushka — {subject}, "
                f"worked in {a['palette']}. Built in layers from her Lane Cove studio "
                f"in Sydney, the surface is developed and reworked so that light seems "
                f"to shift across it as you move.")
    parts.append(sentence)
    if size:
        detail = f"The painting measures {size}"
        if a.get('depthCm'):
            detail += f", {trim_cm(a['depthCm'])} cm deep"
        if frame:
            detail += f", and is presented in a {frame[0].lower() + frame[1:]}"
        detail += '.'
        parts.append(detail)
    if a['status'] == 'sold':
        parts.append('This work has sold. A related painting can be commissioned in a '
                     'comparable size and palette.')
    elif a.get('price'):
        parts.append(f"{money(a['price'], a.get('currency') or 'AUD')}"
                     + (' framed' if a.get('framed') else ' unframed')
                     + ', with insured worldwide shipping quoted on request.')
    else:
        parts.append('Price is available on application.')
    # First paragraph is the artist's own description, where one is recorded.
    if a.get('description') and len(parts) > 1:
        return parts[0] + '\n\n' + ' '.join(parts[1:])
    return ' '.join(parts)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)

    reg = read_register()
    art = load_ts_array('src/data/artworks.ts')
    by_norm = {norm(a['title']): a for a in art}
    by_slug = {a['slug']: a for a in art}

    # Preserve the subject clause from the existing story for reuse.
    def subject_of(a):
        m = re.search(r'— (.+?), worked in ', a.get('story', ''))
        return m.group(1) if m else f"an original work in {a['palette']}"

    # Exact matches first, then fuzzy over what is left — one row per artwork.
    matched, unmatched, taken = {}, [], set()
    pending = []
    for r in reg:
        target = by_norm.get(norm(r['title']))
        if target and target['slug'] not in taken:
            matched[target['slug']] = r
            taken.add(target['slug'])
        else:
            pending.append(r)
    for r in pending:
        pool = [k for k, v in by_norm.items() if v['slug'] not in taken]
        cand = difflib.get_close_matches(norm(r['title']), pool, n=1, cutoff=0.6)
        if not cand:
            unmatched.append(r['title'])
            continue
        target = by_norm[cand[0]]
        matched[target['slug']] = r
        taken.add(target['slug'])

    if unmatched:
        print('!! register rows with no artwork on the site:', unmatched)

    slug_changes = {}
    for a in art:
        r = matched.get(a['slug'])
        if not r:
            print('   no register row for:', a['slug'], '- left unchanged')
            continue

        subject = subject_of(a)
        old_slug = a['slug']

        # Title / slug corrections
        new_slug = SLUG_CORRECTIONS.get(old_slug, old_slug)
        if new_slug in TITLE_OVERRIDES:
            a['title'] = TITLE_OVERRIDES[new_slug]
        if new_slug != old_slug:
            slug_changes[old_slug] = new_slug
            a['slug'] = new_slug
            a['image'] = f'/artworks/{new_slug}.jpg'

        # Recorded physical facts. The photograph is used as an independent
        # check: if the recorded ratio is the inverse of the photographed one,
        # height and width were entered the wrong way round.
        h, w = r['heightCm'], r['widthCm']
        if h and w and a.get('imageWidth') and a.get('imageHeight'):
            photo = a['imageWidth'] / a['imageHeight']
            if abs((w / h) - photo) / photo > 0.12 and abs((h / w) - photo) / photo < 0.12:
                print(f"   !! {a['slug']}: height/width look swapped in the register "
                      f"({h} x {w} cm vs a {'landscape' if photo > 1 else 'portrait'} "
                      f"photograph) — using {w} x {h} cm")
                h, w = w, h
                r['orientation'] = 'landscape' if photo > 1 else 'portrait'
        r['heightCm'], r['widthCm'] = h, w

        a['inventoryId'] = r['inventoryId']
        a['heightCm'] = r['heightCm']
        a['widthCm'] = r['widthCm']
        a['depthCm'] = r['depthCm']
        a['heightIn'] = inches(r['heightCm']) if r['heightCm'] else None
        a['widthIn'] = inches(r['widthCm']) if r['widthCm'] else None
        a['depthIn'] = inches(r['depthCm']) if r['depthCm'] else None
        a['framed'] = r['framed']
        a['frameDescription'] = r['frameDescription']
        a['edition'] = r['edition'] or 'Original'
        a['inspiration'] = r['inspiration']
        a['registerDescription'] = r['description']
        if r['orientation'] in ('landscape', 'portrait', 'square'):
            a['orientation'] = r['orientation']
        # A sold work never carries a price: the achieved price is not recorded in the
        # register, and the modelled list price is not what the buyer paid.
        a['price'] = None if r['sold'] or not r['price'] else int(round(r['price']))
        a['currency'] = r['currency'] or 'AUD'
        a['status'] = ('sold' if r['sold']
                       else 'available' if a['price'] else 'enquire')

        # Copy that now carries the real size
        size = size_phrase({**a})
        coll = a['primaryCollection'].replace('-', ' ')
        a['story'] = build_story({**a, 'description': r['description']}, subject)
        price_txt = money(a['price'], a['currency']) if a['price'] else None
        a['shortDescription'] = (
            f"{a['title']} — an original {coll} painting by Sydney artist Ritushka"
            + (f", {size}" if size else '')
            + (f", {price_txt}." if price_txt else '.' if size
               else '. Enquire for dimensions and price.'))
        subj_cap = subject[0].upper() + subject[1:]
        a['metaDescription'] = (
            f"{a['title']}, an original {coll} painting by Ritushka, contemporary artist in "
            f"Lane Cove, Sydney. {subj_cap}."
            + (f" {size}." if size else '')
            + (' Sold — similar works available to commission.' if a['status'] == 'sold'
               else f' {price_txt}, available now.' if price_txt
               else ' Enquire for price and availability.')
            + ' Ships worldwide.')
        a['alt'] = (f"{a['title']} — original {coll} painting by Ritushka in "
                    f"{a['palette']}" + (f", {size}" if size else ''))

    # Fields for works with no register row yet
    for a in art:
        a.setdefault('inventoryId', None)
        a.setdefault('depthCm', None)
        a.setdefault('heightIn', None)
        a.setdefault('widthIn', None)
        a.setdefault('depthIn', None)
        a.setdefault('framed', False)
        a.setdefault('frameDescription', None)
        a.setdefault('edition', 'Original')
        a.setdefault('inspiration', None)
        a.setdefault('registerDescription', None)
        a.setdefault('price', None)
        a.setdefault('currency', 'AUD')

    # Mockups follow any slug/title change
    mock = load_ts_array('src/data/mockups.ts')
    for m in mock:
        new = slug_changes.get(m['artworkSlug'])
        a = by_slug.get(m['artworkSlug']) or {}
        if new:
            old = m['artworkSlug']
            m['artworkSlug'] = new
            m['slug'] = new + m['slug'][len(old):]
            m['image'] = f"/mockups/{m['slug']}.jpg"
        title = (by_slug.get(m['artworkSlug']) or a).get('title', m['title'])
        room = m['room']
        size = size_phrase(by_slug.get(m['artworkSlug']) or a) if (by_slug.get(m['artworkSlug']) or a) else None
        m['title'] = f"{title} in a {room}"
        m['alt'] = (f"{title} by Ritushka displayed in a {room.lower()}"
                    + (f" — {size}" if size else ''))
        m['seoTitle'] = f"{title} Styled in a {room} | Ritushka"
        m['metaDescription'] = (
            f"See {title}"
            + (f" ({size})" if size else '')
            + f" by Ritushka styled in a {room.lower()}, shown to scale. "
              "Placement and proportion reference for collectors and interior designers. "
              "Enquire to acquire or commission.")

    for a in art:
        a['mockups'] = [m['slug'] for m in mock if m['artworkSlug'] == a['slug']]

    # Rename image assets for corrected slugs
    for old, new in slug_changes.items():
        for folder in ('public/artworks', 'public/mockups'):
            for f in os.listdir(folder):
                if f.startswith(old):
                    src = os.path.join(folder, f)
                    dst = os.path.join(folder, f.replace(old, new, 1))
                    if src != dst and not os.path.exists(dst):
                        os.rename(src, dst)
                        print('   renamed', src, '->', dst)

    # Collections: replace the "sizes on request" copy with the real range
    cols = load_ts_array('src/data/collections.ts')
    for c in cols:
        works = [a for a in art if c['slug'] in a['collections'] and a['heightCm'] and a['widthCm']]
        if not works:
            continue
        smallest = min(works, key=lambda a: a['heightCm'] * a['widthCm'])
        largest = max(works, key=lambda a: a['heightCm'] * a['widthCm'])
        rng = (f"{trim_cm(smallest['heightCm'])} × {trim_cm(smallest['widthCm'])} cm "
               f"to {trim_cm(largest['heightCm'])} × {trim_cm(largest['widthCm'])} cm")
        avail = sum(1 for a in art if c['slug'] in a['collections'] and a['status'] != 'sold')
        priced = [a['price'] for a in art
                  if c['slug'] in a['collections'] and a.get('price')]
        price_rng = (f"Prices in this collection run from {money(min(priced))} to "
                     f"{money(max(priced))}." if len(priced) > 1
                     else f"Works in this collection are {money(priced[0])}." if priced
                     else 'Price is available on application.')
        c['intro'] = re.sub(
            r'(Dimensions, medium and price for any work are available on request\.'
            r'|Works in this collection range from .*?on application\.'
            r'|Works in this collection range from .*?to \$[\d,]+\.)',
            f"Works in this collection range from {rng}, and every painting page lists its "
            f"exact dimensions, depth and framing. {price_rng}",
            c['intro'], count=1)
        for f in c['faqs']:
            if 'cost' in f['q'].lower() or f['q'].lower().startswith('how much'):
                if len(priced) > 1:
                    f['a'] = (f"Original paintings in this collection are "
                              f"{money(min(priced))} to {money(max(priced))} in Australian "
                              f"dollars, listed on each artwork page. Price follows the size "
                              f"of the work: the smallest are {money(min(priced))} and the "
                              f"largest {money(max(priced))}. Every price includes the frame "
                              f"where the work is framed, and a certificate of authenticity. "
                              f"Insured worldwide shipping is quoted separately. Interior "
                              f"designers and trade buyers can apply for trade terms.")
                elif priced:
                    f['a'] = (f"Original paintings in this collection are {money(priced[0])} "
                              f"in Australian dollars, listed on the artwork page, including "
                              f"the frame and a certificate of authenticity. Insured worldwide "
                              f"shipping is quoted separately.")
            if f['q'].lower().startswith('what sizes'):
                f['a'] = (f"This collection ranges from {rng} — {smallest['title']} is the most "
                          f"intimate and {largest['title']} the largest. Exact height, width, depth "
                          f"and framing are listed on every artwork page, and each work is shown "
                          f"to scale in a room mockup. There are currently {avail} works available "
                          f"in this collection.")
    write_ts('src/data/collections.ts', 'collections', 'Collection', cols)

    write_ts('src/data/artworks.ts', 'artworks', 'Artwork', art)
    write_ts('src/data/mockups.ts', 'mockups', 'Mockup', mock)

    # llms.txt: an explicit, machine-readable index of the works with sizes
    all_priced = [a['price'] for a in art if a.get('price')]
    lines = ['## Original works',
             'Every work is an original painting, framed unless noted, shipped worldwide '
             'insured with a certificate of authenticity. Prices are in Australian dollars'
             + (f", from {money(min(all_priced))} to {money(max(all_priced))}."
                if all_priced else '. Price on application.')]
    for a in sorted(art, key=lambda x: -(x['heightCm'] * x['widthCm'] if x['heightCm'] and x['widthCm'] else 0)):
        size = (f"{trim_cm(a['heightCm'])} x {trim_cm(a['widthCm'])} cm"
                if a['heightCm'] and a['widthCm'] else 'size on request')
        state = ('sold' if a['status'] == 'sold'
                 else f"{money(a['price'], a['currency'])}, available" if a.get('price')
                 else 'available, price on application')
        lines.append(f"- {a['title']} — {size}, {state}: /artwork/{a['slug']}")
    block = '\n'.join(lines)
    txt = open('public/llms.txt', encoding='utf-8').read()
    if '## Original works' in txt:
        txt = re.sub(r'## Original works.*?(?=\n## |\Z)', block + '\n\n', txt, flags=re.S)
    else:
        txt = txt.rstrip() + '\n\n' + block + '\n'
    open('public/llms.txt', 'w', encoding='utf-8').write(txt)

    sold = sum(1 for a in art if a['status'] == 'sold')
    sized = sum(1 for a in art if a['heightCm'])
    print(f"register rows {len(reg)} | artworks {len(art)} | with dimensions {sized} | sold {sold}")
    if slug_changes:
        print('slug corrections:', slug_changes)
    json.dump(slug_changes, open('scripts/.slug-redirects.json', 'w'), indent=2)


def _old_of(mapping, new):
    for k, v in mapping.items():
        if v == new:
            return k
    return new


if __name__ == '__main__':
    main()
