// AUTO-GENERATED by scripts/generate-data.mjs — edit the generator or override per-record, do not hand-edit blindly.
import type { Artwork } from './types';
export const artworks: Artwork[] = [
  {
    "id": "aw-001",
    "slug": "dune-hush",
    "title": "Dune Hush",
    "year": 2023,
    "medium": "Acrylic and mixed media on Belgian linen",
    "widthMm": 2000,
    "heightMm": 1500,
    "widthCm": 200,
    "heightCm": 150,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "abstract-landscapes",
      "abstract-seascapes"
    ],
    "primaryCollection": "abstract-landscapes",
    "status": "available",
    "price": 35700,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Dune Hush belongs to Ritushka's Abstract Landscapes series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Dune Hush — 200 × 150cm original abstract landscapes painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Dune Hush | Original Abstract Landscapes Painting by Ritushka",
    "metaDescription": "Dune Hush, a 200×150cm original abstract landscape art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/dune-hush.jpg",
    "alt": "Dune Hush, original abstract landscape art on canvas by Ritushka, 200 by 150 centimetres",
    "mockups": [
      "dune-hush-in-living-room-1"
    ]
  },
  {
    "id": "aw-002",
    "slug": "cloud-hush",
    "title": "Cloud Hush",
    "year": 2024,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 900,
    "heightMm": 1200,
    "widthCm": 90,
    "heightCm": 120,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "available",
    "price": 14400,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Cloud Hush belongs to Ritushka's Abstract Seascapes series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Cloud Hush — 90 × 120cm original abstract seascapes painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Cloud Hush | Original Abstract Seascapes Painting by Ritushka",
    "metaDescription": "Cloud Hush, a 90×120cm original abstract seascape paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/cloud-hush.jpg",
    "alt": "Cloud Hush, original abstract seascape paintings on canvas by Ritushka, 90 by 120 centimetres",
    "mockups": [
      "cloud-hush-in-luxury-home-2"
    ]
  },
  {
    "id": "aw-003",
    "slug": "cloud-murmur",
    "title": "Cloud Murmur",
    "year": 2025,
    "medium": "Mixed media and oil on deep-edge canvas",
    "widthMm": 2000,
    "heightMm": 1500,
    "widthCm": 200,
    "heightCm": 150,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "large-scale-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "large-scale-paintings",
    "status": "sold",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Cloud Murmur belongs to Ritushka's Large Scale Paintings series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Cloud Murmur — 200 × 150cm original large scale paintings painting by Ritushka. Sold; commission a related work.",
    "seoTitle": "Cloud Murmur | Original Large Scale Paintings Painting by Ritushka",
    "metaDescription": "Cloud Murmur, a 200×150cm original large scale art by Sydney artist Ritushka. Sold — similar commissions available. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/cloud-murmur.jpg",
    "alt": "Cloud Murmur, original large scale art on canvas by Ritushka, 200 by 150 centimetres",
    "mockups": [
      "cloud-murmur-in-coastal-home-3"
    ]
  },
  {
    "id": "aw-004",
    "slug": "sea-threshold",
    "title": "Sea Threshold",
    "year": 2026,
    "medium": "Acrylic and mixed media on Belgian linen",
    "widthMm": 2400,
    "heightMm": 1200,
    "widthCm": 240,
    "heightCm": 120,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "coastal-abstract-art",
      "abstract-landscapes"
    ],
    "primaryCollection": "coastal-abstract-art",
    "status": "available",
    "price": 34400,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Sea Threshold belongs to Ritushka's Coastal Abstract Art series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Sea Threshold — 240 × 120cm original coastal abstract art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Sea Threshold | Original Coastal Abstract Art Painting by Ritushka",
    "metaDescription": "Sea Threshold, a 240×120cm original coastal abstract art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/sea-threshold.jpg",
    "alt": "Sea Threshold, original coastal abstract art on canvas by Ritushka, 240 by 120 centimetres",
    "mockups": [
      "sea-threshold-in-modern-apartment-4"
    ]
  },
  {
    "id": "aw-005",
    "slug": "pale-sound",
    "title": "Pale Sound",
    "year": 2023,
    "medium": "Acrylic and mixed media on Belgian linen",
    "widthMm": 2000,
    "heightMm": 1500,
    "widthCm": 200,
    "heightCm": 150,
    "palette": "warm sand, ochre and chalk",
    "collections": [
      "ocean-inspired-paintings",
      "coastal-abstract-art"
    ],
    "primaryCollection": "ocean-inspired-paintings",
    "status": "available",
    "price": 35700,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Pale Sound belongs to Ritushka's Ocean Inspired Paintings series, an exploration of warm sand, ochre and chalk. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Pale Sound — 200 × 150cm original ocean inspired paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Pale Sound | Original Ocean Inspired Paintings Painting by Ritushka",
    "metaDescription": "Pale Sound, a 200×150cm original ocean inspired paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/pale-sound.jpg",
    "alt": "Pale Sound, original ocean inspired paintings on canvas by Ritushka, 200 by 150 centimetres",
    "mockups": [
      "pale-sound-in-architectural-interior-5"
    ]
  },
  {
    "id": "aw-006",
    "slug": "pale-expanse",
    "title": "Pale Expanse",
    "year": 2024,
    "medium": "Acrylic and mixed media on Belgian linen",
    "widthMm": 1000,
    "heightMm": 1000,
    "widthCm": 100,
    "heightCm": 100,
    "palette": "warm sand, ochre and chalk",
    "collections": [
      "contemporary-landscape-art",
      "textured-abstract-paintings"
    ],
    "primaryCollection": "contemporary-landscape-art",
    "status": "available",
    "price": 13500,
    "currency": "AUD",
    "orientation": "square",
    "story": "Pale Expanse belongs to Ritushka's Contemporary Landscape Art series, an exploration of warm sand, ochre and chalk. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Pale Expanse — 100 × 100cm original contemporary landscape art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Pale Expanse | Original Contemporary Landscape Art Painting by Ritushka",
    "metaDescription": "Pale Expanse, a 100×100cm original contemporary landscape art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/pale-expanse.jpg",
    "alt": "Pale Expanse, original contemporary landscape art on canvas by Ritushka, 100 by 100 centimetres",
    "mockups": [
      "pale-expanse-in-commercial-space-6"
    ]
  },
  {
    "id": "aw-007",
    "slug": "echo-veil",
    "title": "Echo Veil",
    "year": 2025,
    "medium": "Acrylic, marble dust and pigment on linen",
    "widthMm": 1830,
    "heightMm": 1220,
    "widthCm": 183,
    "heightCm": 122,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "textured-abstract-paintings",
      "statement-artworks"
    ],
    "primaryCollection": "textured-abstract-paintings",
    "status": "available",
    "price": 27200,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Echo Veil belongs to Ritushka's Textured Abstract Paintings series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Echo Veil — 183 × 122cm original textured abstract paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Echo Veil | Original Textured Abstract Paintings Painting by Ritushka",
    "metaDescription": "Echo Veil, a 183×122cm original textured abstract paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/echo-veil.jpg",
    "alt": "Echo Veil, original textured abstract paintings on canvas by Ritushka, 183 by 122 centimetres",
    "mockups": [
      "echo-veil-in-designer-space-7"
    ]
  },
  {
    "id": "aw-008",
    "slug": "dune-hollow",
    "title": "Dune Hollow",
    "year": 2026,
    "medium": "Acrylic with raw pigment on cotton canvas",
    "widthMm": 2400,
    "heightMm": 1200,
    "widthCm": 240,
    "heightCm": 120,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "blue-abstract-paintings",
      "large-scale-paintings"
    ],
    "primaryCollection": "blue-abstract-paintings",
    "status": "available",
    "price": 34400,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Dune Hollow belongs to Ritushka's Blue Abstract Paintings series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Dune Hollow — 240 × 120cm original blue abstract paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Dune Hollow | Original Blue Abstract Paintings Painting by Ritushka",
    "metaDescription": "Dune Hollow, a 240×120cm original blue abstract paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/dune-hollow.jpg",
    "alt": "Dune Hollow, original blue abstract paintings on canvas by Ritushka, 240 by 120 centimetres",
    "mockups": [
      "dune-hollow-in-penthouse-8"
    ]
  },
  {
    "id": "aw-009",
    "slug": "windward-hollow",
    "title": "Windward Hollow",
    "year": 2023,
    "medium": "Mixed media and oil on deep-edge canvas",
    "widthMm": 2000,
    "heightMm": 1500,
    "widthCm": 200,
    "heightCm": 150,
    "palette": "warm sand, ochre and chalk",
    "collections": [
      "modern-australian-art",
      "contemporary-landscape-art"
    ],
    "primaryCollection": "modern-australian-art",
    "status": "available",
    "price": 35700,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Windward Hollow belongs to Ritushka's Modern Australian Art series, an exploration of warm sand, ochre and chalk. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Windward Hollow — 200 × 150cm original modern australian art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Windward Hollow | Original Modern Australian Art Painting by Ritushka",
    "metaDescription": "Windward Hollow, a 200×150cm original modern australian art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/windward-hollow.jpg",
    "alt": "Windward Hollow, original modern australian art on canvas by Ritushka, 200 by 150 centimetres",
    "mockups": [
      "windward-hollow-in-hotel-lobby-9"
    ]
  },
  {
    "id": "aw-010",
    "slug": "high-passage",
    "title": "High Passage",
    "year": 2024,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 760,
    "heightMm": 1015,
    "widthCm": 76,
    "heightCm": 102,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "statement-artworks",
      "modern-australian-art"
    ],
    "primaryCollection": "statement-artworks",
    "status": "available",
    "price": 11000,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "High Passage belongs to Ritushka's Statement Artworks series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "High Passage — 76 × 102cm original statement artworks painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "High Passage | Original Statement Artworks Painting by Ritushka",
    "metaDescription": "High Passage, a 76×102cm original statement artwork by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/high-passage.jpg",
    "alt": "High Passage, original statement artwork on canvas by Ritushka, 76 by 102 centimetres",
    "mockups": [
      "high-passage-in-boardroom-10"
    ]
  },
  {
    "id": "aw-011",
    "slug": "northern-mirage",
    "title": "Northern Mirage",
    "year": 2025,
    "medium": "Acrylic and mixed media on Belgian linen",
    "widthMm": 2400,
    "heightMm": 1200,
    "widthCm": 240,
    "heightCm": 120,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "abstract-landscapes",
      "abstract-seascapes"
    ],
    "primaryCollection": "abstract-landscapes",
    "status": "available",
    "price": 34400,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Northern Mirage belongs to Ritushka's Abstract Landscapes series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Northern Mirage — 240 × 120cm original abstract landscapes painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Northern Mirage | Original Abstract Landscapes Painting by Ritushka",
    "metaDescription": "Northern Mirage, a 240×120cm original abstract landscape art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/northern-mirage.jpg",
    "alt": "Northern Mirage, original abstract landscape art on canvas by Ritushka, 240 by 120 centimetres",
    "mockups": [
      "northern-mirage-in-living-room-11"
    ]
  },
  {
    "id": "aw-012",
    "slug": "echo-expanse",
    "title": "Echo Expanse",
    "year": 2026,
    "medium": "Acrylic with raw pigment on cotton canvas",
    "widthMm": 1000,
    "heightMm": 1000,
    "widthCm": 100,
    "heightCm": 100,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "available",
    "price": 13500,
    "currency": "AUD",
    "orientation": "square",
    "story": "Echo Expanse belongs to Ritushka's Abstract Seascapes series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Echo Expanse — 100 × 100cm original abstract seascapes painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Echo Expanse | Original Abstract Seascapes Painting by Ritushka",
    "metaDescription": "Echo Expanse, a 100×100cm original abstract seascape paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/echo-expanse.jpg",
    "alt": "Echo Expanse, original abstract seascape paintings on canvas by Ritushka, 100 by 100 centimetres",
    "mockups": [
      "echo-expanse-in-luxury-home-12"
    ]
  },
  {
    "id": "aw-013",
    "slug": "drift-mirage",
    "title": "Drift Mirage",
    "year": 2023,
    "medium": "Mixed media and oil on deep-edge canvas",
    "widthMm": 2100,
    "heightMm": 1400,
    "widthCm": 210,
    "heightCm": 140,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "large-scale-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "large-scale-paintings",
    "status": "sold",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Drift Mirage belongs to Ritushka's Large Scale Paintings series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Drift Mirage — 210 × 140cm original large scale paintings painting by Ritushka. Sold; commission a related work.",
    "seoTitle": "Drift Mirage | Original Large Scale Paintings Painting by Ritushka",
    "metaDescription": "Drift Mirage, a 210×140cm original large scale art by Sydney artist Ritushka. Sold — similar commissions available. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/drift-mirage.jpg",
    "alt": "Drift Mirage, original large scale art on canvas by Ritushka, 210 by 140 centimetres",
    "mockups": [
      "drift-mirage-in-coastal-home-13"
    ]
  },
  {
    "id": "aw-014",
    "slug": "shoreline-hollow",
    "title": "Shoreline Hollow",
    "year": 2024,
    "medium": "Acrylic and mixed media on Belgian linen",
    "widthMm": 1830,
    "heightMm": 1830,
    "widthCm": 183,
    "heightCm": 183,
    "palette": "indigo, teal and bleached coral",
    "collections": [
      "coastal-abstract-art",
      "abstract-landscapes"
    ],
    "primaryCollection": "coastal-abstract-art",
    "status": "available",
    "price": 39600,
    "currency": "AUD",
    "orientation": "square",
    "story": "Shoreline Hollow belongs to Ritushka's Coastal Abstract Art series, an exploration of indigo, teal and bleached coral. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Shoreline Hollow — 183 × 183cm original coastal abstract art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Shoreline Hollow | Original Coastal Abstract Art Painting by Ritushka",
    "metaDescription": "Shoreline Hollow, a 183×183cm original coastal abstract art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/shoreline-hollow.jpg",
    "alt": "Shoreline Hollow, original coastal abstract art on canvas by Ritushka, 183 by 183 centimetres",
    "mockups": [
      "shoreline-hollow-in-modern-apartment-14"
    ]
  },
  {
    "id": "aw-015",
    "slug": "saltwater-rhythm",
    "title": "Saltwater Rhythm",
    "year": 2025,
    "medium": "Acrylic, marble dust and pigment on linen",
    "widthMm": 2100,
    "heightMm": 1400,
    "widthCm": 210,
    "heightCm": 140,
    "palette": "warm sand, ochre and chalk",
    "collections": [
      "ocean-inspired-paintings",
      "coastal-abstract-art"
    ],
    "primaryCollection": "ocean-inspired-paintings",
    "status": "available",
    "price": 35100,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Saltwater Rhythm belongs to Ritushka's Ocean Inspired Paintings series, an exploration of warm sand, ochre and chalk. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Saltwater Rhythm — 210 × 140cm original ocean inspired paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Saltwater Rhythm | Original Ocean Inspired Paintings Painting by Ritushka",
    "metaDescription": "Saltwater Rhythm, a 210×140cm original ocean inspired paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/saltwater-rhythm.jpg",
    "alt": "Saltwater Rhythm, original ocean inspired paintings on canvas by Ritushka, 210 by 140 centimetres",
    "mockups": [
      "saltwater-rhythm-in-architectural-interior-15"
    ]
  },
  {
    "id": "aw-016",
    "slug": "saltwater-span",
    "title": "Saltwater Span",
    "year": 2026,
    "medium": "Acrylic and mixed media on Belgian linen",
    "widthMm": 1830,
    "heightMm": 1220,
    "widthCm": 183,
    "heightCm": 122,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "contemporary-landscape-art",
      "textured-abstract-paintings"
    ],
    "primaryCollection": "contemporary-landscape-art",
    "status": "available",
    "price": 27200,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Saltwater Span belongs to Ritushka's Contemporary Landscape Art series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Saltwater Span — 183 × 122cm original contemporary landscape art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Saltwater Span | Original Contemporary Landscape Art Painting by Ritushka",
    "metaDescription": "Saltwater Span, a 183×122cm original contemporary landscape art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/saltwater-span.jpg",
    "alt": "Saltwater Span, original contemporary landscape art on canvas by Ritushka, 183 by 122 centimetres",
    "mockups": [
      "saltwater-span-in-commercial-space-16"
    ]
  },
  {
    "id": "aw-017",
    "slug": "low-murmur",
    "title": "Low Murmur",
    "year": 2023,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 1520,
    "heightMm": 1020,
    "widthCm": 152,
    "heightCm": 102,
    "palette": "soft bone whites, sea-foam and deep ocean blue",
    "collections": [
      "textured-abstract-paintings",
      "statement-artworks"
    ],
    "primaryCollection": "textured-abstract-paintings",
    "status": "available",
    "price": 19600,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Low Murmur belongs to Ritushka's Textured Abstract Paintings series, an exploration of soft bone whites, sea-foam and deep ocean blue. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Low Murmur — 152 × 102cm original textured abstract paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Low Murmur | Original Textured Abstract Paintings Painting by Ritushka",
    "metaDescription": "Low Murmur, a 152×102cm original textured abstract paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/low-murmur.jpg",
    "alt": "Low Murmur, original textured abstract paintings on canvas by Ritushka, 152 by 102 centimetres",
    "mockups": [
      "low-murmur-in-designer-space-17"
    ]
  },
  {
    "id": "aw-018",
    "slug": "field-hollow",
    "title": "Field Hollow",
    "year": 2024,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 900,
    "heightMm": 1200,
    "widthCm": 90,
    "heightCm": 120,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "blue-abstract-paintings",
      "large-scale-paintings"
    ],
    "primaryCollection": "blue-abstract-paintings",
    "status": "sold",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Field Hollow belongs to Ritushka's Blue Abstract Paintings series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Field Hollow — 90 × 120cm original blue abstract paintings painting by Ritushka. Sold; commission a related work.",
    "seoTitle": "Field Hollow | Original Blue Abstract Paintings Painting by Ritushka",
    "metaDescription": "Field Hollow, a 90×120cm original blue abstract paintings by Sydney artist Ritushka. Sold — similar commissions available. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/field-hollow.jpg",
    "alt": "Field Hollow, original blue abstract paintings on canvas by Ritushka, 90 by 120 centimetres",
    "mockups": [
      "field-hollow-in-penthouse-18"
    ]
  },
  {
    "id": "aw-019",
    "slug": "field-cadence",
    "title": "Field Cadence",
    "year": 2025,
    "medium": "Acrylic, marble dust and pigment on linen",
    "widthMm": 1830,
    "heightMm": 1220,
    "widthCm": 183,
    "heightCm": 122,
    "palette": "warm sand, ochre and chalk",
    "collections": [
      "modern-australian-art",
      "contemporary-landscape-art"
    ],
    "primaryCollection": "modern-australian-art",
    "status": "available",
    "price": 27200,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Field Cadence belongs to Ritushka's Modern Australian Art series, an exploration of warm sand, ochre and chalk. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Field Cadence — 183 × 122cm original modern australian art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Field Cadence | Original Modern Australian Art Painting by Ritushka",
    "metaDescription": "Field Cadence, a 183×122cm original modern australian art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/field-cadence.jpg",
    "alt": "Field Cadence, original modern australian art on canvas by Ritushka, 183 by 122 centimetres",
    "mockups": [
      "field-cadence-in-hotel-lobby-19"
    ]
  },
  {
    "id": "aw-020",
    "slug": "estuary-sound",
    "title": "Estuary Sound",
    "year": 2026,
    "medium": "Acrylic and mixed media on Belgian linen",
    "widthMm": 760,
    "heightMm": 1015,
    "widthCm": 76,
    "heightCm": 102,
    "palette": "soft bone whites, sea-foam and deep ocean blue",
    "collections": [
      "statement-artworks",
      "modern-australian-art"
    ],
    "primaryCollection": "statement-artworks",
    "status": "available",
    "price": 11000,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Estuary Sound belongs to Ritushka's Statement Artworks series, an exploration of soft bone whites, sea-foam and deep ocean blue. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Estuary Sound — 76 × 102cm original statement artworks painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Estuary Sound | Original Statement Artworks Painting by Ritushka",
    "metaDescription": "Estuary Sound, a 76×102cm original statement artwork by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/estuary-sound.jpg",
    "alt": "Estuary Sound, original statement artwork on canvas by Ritushka, 76 by 102 centimetres",
    "mockups": [
      "estuary-sound-in-boardroom-20"
    ]
  },
  {
    "id": "aw-021",
    "slug": "estuary-current",
    "title": "Estuary Current",
    "year": 2023,
    "medium": "Acrylic, marble dust and pigment on linen",
    "widthMm": 2100,
    "heightMm": 1400,
    "widthCm": 210,
    "heightCm": 140,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "abstract-landscapes",
      "abstract-seascapes"
    ],
    "primaryCollection": "abstract-landscapes",
    "status": "sold",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Estuary Current belongs to Ritushka's Abstract Landscapes series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Estuary Current — 210 × 140cm original abstract landscapes painting by Ritushka. Sold; commission a related work.",
    "seoTitle": "Estuary Current | Original Abstract Landscapes Painting by Ritushka",
    "metaDescription": "Estuary Current, a 210×140cm original abstract landscape art by Sydney artist Ritushka. Sold — similar commissions available. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/estuary-current.jpg",
    "alt": "Estuary Current, original abstract landscape art on canvas by Ritushka, 210 by 140 centimetres",
    "mockups": [
      "estuary-current-in-living-room-21"
    ]
  },
  {
    "id": "aw-022",
    "slug": "estuary-light",
    "title": "Estuary Light",
    "year": 2024,
    "medium": "Mixed media and oil on deep-edge canvas",
    "widthMm": 1370,
    "heightMm": 1830,
    "widthCm": 137,
    "heightCm": 183,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "available",
    "price": 30300,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Estuary Light belongs to Ritushka's Abstract Seascapes series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Estuary Light — 137 × 183cm original abstract seascapes painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Estuary Light | Original Abstract Seascapes Painting by Ritushka",
    "metaDescription": "Estuary Light, a 137×183cm original abstract seascape paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/estuary-light.jpg",
    "alt": "Estuary Light, original abstract seascape paintings on canvas by Ritushka, 137 by 183 centimetres",
    "mockups": [
      "estuary-light-in-luxury-home-22"
    ]
  },
  {
    "id": "aw-023",
    "slug": "quiet-drift",
    "title": "Quiet Drift",
    "year": 2025,
    "medium": "Acrylic with raw pigment on cotton canvas",
    "widthMm": 2000,
    "heightMm": 1500,
    "widthCm": 200,
    "heightCm": 150,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "large-scale-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "large-scale-paintings",
    "status": "sold",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Quiet Drift belongs to Ritushka's Large Scale Paintings series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Quiet Drift — 200 × 150cm original large scale paintings painting by Ritushka. Sold; commission a related work.",
    "seoTitle": "Quiet Drift | Original Large Scale Paintings Painting by Ritushka",
    "metaDescription": "Quiet Drift, a 200×150cm original large scale art by Sydney artist Ritushka. Sold — similar commissions available. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/quiet-drift.jpg",
    "alt": "Quiet Drift, original large scale art on canvas by Ritushka, 200 by 150 centimetres",
    "mockups": [
      "quiet-drift-in-coastal-home-23"
    ]
  },
  {
    "id": "aw-024",
    "slug": "low-tide",
    "title": "Low Tide",
    "year": 2026,
    "medium": "Acrylic, marble dust and pigment on linen",
    "widthMm": 2000,
    "heightMm": 1500,
    "widthCm": 200,
    "heightCm": 150,
    "palette": "indigo, teal and bleached coral",
    "collections": [
      "coastal-abstract-art",
      "abstract-landscapes"
    ],
    "primaryCollection": "coastal-abstract-art",
    "status": "sold",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Low Tide belongs to Ritushka's Coastal Abstract Art series, an exploration of indigo, teal and bleached coral. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Low Tide — 200 × 150cm original coastal abstract art painting by Ritushka. Sold; commission a related work.",
    "seoTitle": "Low Tide | Original Coastal Abstract Art Painting by Ritushka",
    "metaDescription": "Low Tide, a 200×150cm original coastal abstract art by Sydney artist Ritushka. Sold — similar commissions available. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/low-tide.jpg",
    "alt": "Low Tide, original coastal abstract art on canvas by Ritushka, 200 by 150 centimetres",
    "mockups": [
      "low-tide-in-modern-apartment-24"
    ]
  },
  {
    "id": "aw-025",
    "slug": "low-rhythm",
    "title": "Low Rhythm",
    "year": 2023,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 1830,
    "heightMm": 1830,
    "widthCm": 183,
    "heightCm": 183,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "ocean-inspired-paintings",
      "coastal-abstract-art"
    ],
    "primaryCollection": "ocean-inspired-paintings",
    "status": "available",
    "price": 39600,
    "currency": "AUD",
    "orientation": "square",
    "story": "Low Rhythm belongs to Ritushka's Ocean Inspired Paintings series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Low Rhythm — 183 × 183cm original ocean inspired paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Low Rhythm | Original Ocean Inspired Paintings Painting by Ritushka",
    "metaDescription": "Low Rhythm, a 183×183cm original ocean inspired paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/low-rhythm.jpg",
    "alt": "Low Rhythm, original ocean inspired paintings on canvas by Ritushka, 183 by 183 centimetres",
    "mockups": [
      "low-rhythm-in-architectural-interior-25"
    ]
  },
  {
    "id": "aw-026",
    "slug": "morning-hush",
    "title": "Morning Hush",
    "year": 2024,
    "medium": "Acrylic, marble dust and pigment on linen",
    "widthMm": 2100,
    "heightMm": 1400,
    "widthCm": 210,
    "heightCm": 140,
    "palette": "soft bone whites, sea-foam and deep ocean blue",
    "collections": [
      "contemporary-landscape-art",
      "textured-abstract-paintings"
    ],
    "primaryCollection": "contemporary-landscape-art",
    "status": "sold",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Morning Hush belongs to Ritushka's Contemporary Landscape Art series, an exploration of soft bone whites, sea-foam and deep ocean blue. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Morning Hush — 210 × 140cm original contemporary landscape art painting by Ritushka. Sold; commission a related work.",
    "seoTitle": "Morning Hush | Original Contemporary Landscape Art Painting by Ritushka",
    "metaDescription": "Morning Hush, a 210×140cm original contemporary landscape art by Sydney artist Ritushka. Sold — similar commissions available. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/morning-hush.jpg",
    "alt": "Morning Hush, original contemporary landscape art on canvas by Ritushka, 210 by 140 centimetres",
    "mockups": [
      "morning-hush-in-commercial-space-26"
    ]
  },
  {
    "id": "aw-027",
    "slug": "horizon-drift",
    "title": "Horizon Drift",
    "year": 2025,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 1830,
    "heightMm": 1220,
    "widthCm": 183,
    "heightCm": 122,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "textured-abstract-paintings",
      "statement-artworks"
    ],
    "primaryCollection": "textured-abstract-paintings",
    "status": "available",
    "price": 27200,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Horizon Drift belongs to Ritushka's Textured Abstract Paintings series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Horizon Drift — 183 × 122cm original textured abstract paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Horizon Drift | Original Textured Abstract Paintings Painting by Ritushka",
    "metaDescription": "Horizon Drift, a 183×122cm original textured abstract paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/horizon-drift.jpg",
    "alt": "Horizon Drift, original textured abstract paintings on canvas by Ritushka, 183 by 122 centimetres",
    "mockups": [
      "horizon-drift-in-designer-space-27"
    ]
  },
  {
    "id": "aw-028",
    "slug": "marble-whisper",
    "title": "Marble Whisper",
    "year": 2026,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 1830,
    "heightMm": 1830,
    "widthCm": 183,
    "heightCm": 183,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "blue-abstract-paintings",
      "large-scale-paintings"
    ],
    "primaryCollection": "blue-abstract-paintings",
    "status": "available",
    "price": 39600,
    "currency": "AUD",
    "orientation": "square",
    "story": "Marble Whisper belongs to Ritushka's Blue Abstract Paintings series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Marble Whisper — 183 × 183cm original blue abstract paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Marble Whisper | Original Blue Abstract Paintings Painting by Ritushka",
    "metaDescription": "Marble Whisper, a 183×183cm original blue abstract paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/marble-whisper.jpg",
    "alt": "Marble Whisper, original blue abstract paintings on canvas by Ritushka, 183 by 183 centimetres",
    "mockups": [
      "marble-whisper-in-penthouse-28"
    ]
  },
  {
    "id": "aw-029",
    "slug": "shoreline-mirage",
    "title": "Shoreline Mirage",
    "year": 2023,
    "medium": "Mixed media and oil on deep-edge canvas",
    "widthMm": 760,
    "heightMm": 1015,
    "widthCm": 76,
    "heightCm": 102,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "modern-australian-art",
      "contemporary-landscape-art"
    ],
    "primaryCollection": "modern-australian-art",
    "status": "reserved",
    "price": 11000,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Shoreline Mirage belongs to Ritushka's Modern Australian Art series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Shoreline Mirage — 76 × 102cm original modern australian art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Shoreline Mirage | Original Modern Australian Art Painting by Ritushka",
    "metaDescription": "Shoreline Mirage, a 76×102cm original modern australian art by Sydney artist Ritushka. Reserved. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/shoreline-mirage.jpg",
    "alt": "Shoreline Mirage, original modern australian art on canvas by Ritushka, 76 by 102 centimetres",
    "mockups": [
      "shoreline-mirage-in-hotel-lobby-29"
    ]
  },
  {
    "id": "aw-030",
    "slug": "quiet-verge",
    "title": "Quiet Verge",
    "year": 2024,
    "medium": "Mixed media and oil on deep-edge canvas",
    "widthMm": 2100,
    "heightMm": 1400,
    "widthCm": 210,
    "heightCm": 140,
    "palette": "indigo, teal and bleached coral",
    "collections": [
      "statement-artworks",
      "modern-australian-art"
    ],
    "primaryCollection": "statement-artworks",
    "status": "available",
    "price": 35100,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Quiet Verge belongs to Ritushka's Statement Artworks series, an exploration of indigo, teal and bleached coral. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Quiet Verge — 210 × 140cm original statement artworks painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Quiet Verge | Original Statement Artworks Painting by Ritushka",
    "metaDescription": "Quiet Verge, a 210×140cm original statement artwork by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/quiet-verge.jpg",
    "alt": "Quiet Verge, original statement artwork on canvas by Ritushka, 210 by 140 centimetres",
    "mockups": [
      "quiet-verge-in-boardroom-30"
    ]
  },
  {
    "id": "aw-031",
    "slug": "field-threshold",
    "title": "Field Threshold",
    "year": 2025,
    "medium": "Acrylic with raw pigment on cotton canvas",
    "widthMm": 1830,
    "heightMm": 1220,
    "widthCm": 183,
    "heightCm": 122,
    "palette": "soft bone whites, sea-foam and deep ocean blue",
    "collections": [
      "abstract-landscapes",
      "abstract-seascapes"
    ],
    "primaryCollection": "abstract-landscapes",
    "status": "available",
    "price": 27200,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Field Threshold belongs to Ritushka's Abstract Landscapes series, an exploration of soft bone whites, sea-foam and deep ocean blue. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Field Threshold — 183 × 122cm original abstract landscapes painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Field Threshold | Original Abstract Landscapes Painting by Ritushka",
    "metaDescription": "Field Threshold, a 183×122cm original abstract landscape art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/field-threshold.jpg",
    "alt": "Field Threshold, original abstract landscape art on canvas by Ritushka, 183 by 122 centimetres",
    "mockups": [
      "field-threshold-in-living-room-31"
    ]
  },
  {
    "id": "aw-032",
    "slug": "high-fold",
    "title": "High Fold",
    "year": 2026,
    "medium": "Acrylic and mixed media on Belgian linen",
    "widthMm": 1000,
    "heightMm": 1000,
    "widthCm": 100,
    "heightCm": 100,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "available",
    "price": 13500,
    "currency": "AUD",
    "orientation": "square",
    "story": "High Fold belongs to Ritushka's Abstract Seascapes series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "High Fold — 100 × 100cm original abstract seascapes painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "High Fold | Original Abstract Seascapes Painting by Ritushka",
    "metaDescription": "High Fold, a 100×100cm original abstract seascape paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/high-fold.jpg",
    "alt": "High Fold, original abstract seascape paintings on canvas by Ritushka, 100 by 100 centimetres",
    "mockups": [
      "high-fold-in-luxury-home-32"
    ]
  },
  {
    "id": "aw-033",
    "slug": "quiet-passage",
    "title": "Quiet Passage",
    "year": 2023,
    "medium": "Acrylic, marble dust and pigment on linen",
    "widthMm": 1000,
    "heightMm": 1000,
    "widthCm": 100,
    "heightCm": 100,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "large-scale-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "large-scale-paintings",
    "status": "sold",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Quiet Passage belongs to Ritushka's Large Scale Paintings series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Quiet Passage — 100 × 100cm original large scale paintings painting by Ritushka. Sold; commission a related work.",
    "seoTitle": "Quiet Passage | Original Large Scale Paintings Painting by Ritushka",
    "metaDescription": "Quiet Passage, a 100×100cm original large scale art by Sydney artist Ritushka. Sold — similar commissions available. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/quiet-passage.jpg",
    "alt": "Quiet Passage, original large scale art on canvas by Ritushka, 100 by 100 centimetres",
    "mockups": [
      "quiet-passage-in-coastal-home-33"
    ]
  },
  {
    "id": "aw-034",
    "slug": "field-sound",
    "title": "Field Sound",
    "year": 2024,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 1830,
    "heightMm": 1220,
    "widthCm": 183,
    "heightCm": 122,
    "palette": "warm sand, ochre and chalk",
    "collections": [
      "coastal-abstract-art",
      "abstract-landscapes"
    ],
    "primaryCollection": "coastal-abstract-art",
    "status": "available",
    "price": 27200,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Field Sound belongs to Ritushka's Coastal Abstract Art series, an exploration of warm sand, ochre and chalk. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Field Sound — 183 × 122cm original coastal abstract art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Field Sound | Original Coastal Abstract Art Painting by Ritushka",
    "metaDescription": "Field Sound, a 183×122cm original coastal abstract art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/field-sound.jpg",
    "alt": "Field Sound, original coastal abstract art on canvas by Ritushka, 183 by 122 centimetres",
    "mockups": [
      "field-sound-in-modern-apartment-34"
    ]
  },
  {
    "id": "aw-035",
    "slug": "low-drift",
    "title": "Low Drift",
    "year": 2025,
    "medium": "Acrylic with raw pigment on cotton canvas",
    "widthMm": 1370,
    "heightMm": 1830,
    "widthCm": 137,
    "heightCm": 183,
    "palette": "indigo, teal and bleached coral",
    "collections": [
      "ocean-inspired-paintings",
      "coastal-abstract-art"
    ],
    "primaryCollection": "ocean-inspired-paintings",
    "status": "available",
    "price": 30300,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Low Drift belongs to Ritushka's Ocean Inspired Paintings series, an exploration of indigo, teal and bleached coral. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Low Drift — 137 × 183cm original ocean inspired paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Low Drift | Original Ocean Inspired Paintings Painting by Ritushka",
    "metaDescription": "Low Drift, a 137×183cm original ocean inspired paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/low-drift.jpg",
    "alt": "Low Drift, original ocean inspired paintings on canvas by Ritushka, 137 by 183 centimetres",
    "mockups": [
      "low-drift-in-architectural-interior-35"
    ]
  },
  {
    "id": "aw-036",
    "slug": "high-bloom",
    "title": "High Bloom",
    "year": 2026,
    "medium": "Mixed media and oil on deep-edge canvas",
    "widthMm": 1000,
    "heightMm": 1000,
    "widthCm": 100,
    "heightCm": 100,
    "palette": "slate greys, mist and pale silver",
    "collections": [
      "contemporary-landscape-art",
      "textured-abstract-paintings"
    ],
    "primaryCollection": "contemporary-landscape-art",
    "status": "available",
    "price": 13500,
    "currency": "AUD",
    "orientation": "square",
    "story": "High Bloom belongs to Ritushka's Contemporary Landscape Art series, an exploration of slate greys, mist and pale silver. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "High Bloom — 100 × 100cm original contemporary landscape art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "High Bloom | Original Contemporary Landscape Art Painting by Ritushka",
    "metaDescription": "High Bloom, a 100×100cm original contemporary landscape art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/high-bloom.jpg",
    "alt": "High Bloom, original contemporary landscape art on canvas by Ritushka, 100 by 100 centimetres",
    "mockups": [
      "high-bloom-in-commercial-space-36"
    ]
  },
  {
    "id": "aw-037",
    "slug": "estuary-atlas",
    "title": "Estuary Atlas",
    "year": 2023,
    "medium": "Acrylic with raw pigment on cotton canvas",
    "widthMm": 1520,
    "heightMm": 1020,
    "widthCm": 152,
    "heightCm": 102,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "textured-abstract-paintings",
      "statement-artworks"
    ],
    "primaryCollection": "textured-abstract-paintings",
    "status": "available",
    "price": 19600,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Estuary Atlas belongs to Ritushka's Textured Abstract Paintings series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Estuary Atlas — 152 × 102cm original textured abstract paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Estuary Atlas | Original Textured Abstract Paintings Painting by Ritushka",
    "metaDescription": "Estuary Atlas, a 152×102cm original textured abstract paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/estuary-atlas.jpg",
    "alt": "Estuary Atlas, original textured abstract paintings on canvas by Ritushka, 152 by 102 centimetres",
    "mockups": [
      "estuary-atlas-in-designer-space-37"
    ]
  },
  {
    "id": "aw-038",
    "slug": "coastal-whisper",
    "title": "Coastal Whisper",
    "year": 2024,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 2400,
    "heightMm": 1200,
    "widthCm": 240,
    "heightCm": 120,
    "palette": "warm sand, ochre and chalk",
    "collections": [
      "blue-abstract-paintings",
      "large-scale-paintings"
    ],
    "primaryCollection": "blue-abstract-paintings",
    "status": "available",
    "price": 34400,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Coastal Whisper belongs to Ritushka's Blue Abstract Paintings series, an exploration of warm sand, ochre and chalk. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Coastal Whisper — 240 × 120cm original blue abstract paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Coastal Whisper | Original Blue Abstract Paintings Painting by Ritushka",
    "metaDescription": "Coastal Whisper, a 240×120cm original blue abstract paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/coastal-whisper.jpg",
    "alt": "Coastal Whisper, original blue abstract paintings on canvas by Ritushka, 240 by 120 centimetres",
    "mockups": [
      "coastal-whisper-in-penthouse-38"
    ]
  },
  {
    "id": "aw-039",
    "slug": "high-murmur",
    "title": "High Murmur",
    "year": 2025,
    "medium": "Acrylic with raw pigment on cotton canvas",
    "widthMm": 760,
    "heightMm": 1015,
    "widthCm": 76,
    "heightCm": 102,
    "palette": "soft bone whites, sea-foam and deep ocean blue",
    "collections": [
      "modern-australian-art",
      "contemporary-landscape-art"
    ],
    "primaryCollection": "modern-australian-art",
    "status": "available",
    "price": 11000,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "High Murmur belongs to Ritushka's Modern Australian Art series, an exploration of soft bone whites, sea-foam and deep ocean blue. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "High Murmur — 76 × 102cm original modern australian art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "High Murmur | Original Modern Australian Art Painting by Ritushka",
    "metaDescription": "High Murmur, a 76×102cm original modern australian art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/high-murmur.jpg",
    "alt": "High Murmur, original modern australian art on canvas by Ritushka, 76 by 102 centimetres",
    "mockups": [
      "high-murmur-in-hotel-lobby-39"
    ]
  },
  {
    "id": "aw-040",
    "slug": "morning-verge",
    "title": "Morning Verge",
    "year": 2026,
    "medium": "Acrylic and mixed media on Belgian linen",
    "widthMm": 2000,
    "heightMm": 1500,
    "widthCm": 200,
    "heightCm": 150,
    "palette": "soft bone whites, sea-foam and deep ocean blue",
    "collections": [
      "statement-artworks",
      "modern-australian-art"
    ],
    "primaryCollection": "statement-artworks",
    "status": "reserved",
    "price": 35700,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Morning Verge belongs to Ritushka's Statement Artworks series, an exploration of soft bone whites, sea-foam and deep ocean blue. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Morning Verge — 200 × 150cm original statement artworks painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Morning Verge | Original Statement Artworks Painting by Ritushka",
    "metaDescription": "Morning Verge, a 200×150cm original statement artwork by Sydney artist Ritushka. Reserved. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/morning-verge.jpg",
    "alt": "Morning Verge, original statement artwork on canvas by Ritushka, 200 by 150 centimetres",
    "mockups": [
      "morning-verge-in-boardroom-40"
    ]
  },
  {
    "id": "aw-041",
    "slug": "estuary-mirage",
    "title": "Estuary Mirage",
    "year": 2023,
    "medium": "Acrylic, marble dust and pigment on linen",
    "widthMm": 760,
    "heightMm": 1015,
    "widthCm": 76,
    "heightCm": 102,
    "palette": "soft bone whites, sea-foam and deep ocean blue",
    "collections": [
      "abstract-landscapes",
      "abstract-seascapes"
    ],
    "primaryCollection": "abstract-landscapes",
    "status": "available",
    "price": 11000,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Estuary Mirage belongs to Ritushka's Abstract Landscapes series, an exploration of soft bone whites, sea-foam and deep ocean blue. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Estuary Mirage — 76 × 102cm original abstract landscapes painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Estuary Mirage | Original Abstract Landscapes Painting by Ritushka",
    "metaDescription": "Estuary Mirage, a 76×102cm original abstract landscape art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/estuary-mirage.jpg",
    "alt": "Estuary Mirage, original abstract landscape art on canvas by Ritushka, 76 by 102 centimetres",
    "mockups": [
      "estuary-mirage-in-living-room-41"
    ]
  },
  {
    "id": "aw-042",
    "slug": "shoreline-hush",
    "title": "Shoreline Hush",
    "year": 2024,
    "medium": "Acrylic, marble dust and pigment on linen",
    "widthMm": 1830,
    "heightMm": 1830,
    "widthCm": 183,
    "heightCm": 183,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "available",
    "price": 39600,
    "currency": "AUD",
    "orientation": "square",
    "story": "Shoreline Hush belongs to Ritushka's Abstract Seascapes series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Shoreline Hush — 183 × 183cm original abstract seascapes painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Shoreline Hush | Original Abstract Seascapes Painting by Ritushka",
    "metaDescription": "Shoreline Hush, a 183×183cm original abstract seascape paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/shoreline-hush.jpg",
    "alt": "Shoreline Hush, original abstract seascape paintings on canvas by Ritushka, 183 by 183 centimetres",
    "mockups": [
      "shoreline-hush-in-luxury-home-42"
    ]
  },
  {
    "id": "aw-043",
    "slug": "horizon-span",
    "title": "Horizon Span",
    "year": 2025,
    "medium": "Mixed media and oil on deep-edge canvas",
    "widthMm": 1000,
    "heightMm": 1000,
    "widthCm": 100,
    "heightCm": 100,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "large-scale-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "large-scale-paintings",
    "status": "available",
    "price": 13500,
    "currency": "AUD",
    "orientation": "square",
    "story": "Horizon Span belongs to Ritushka's Large Scale Paintings series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Horizon Span — 100 × 100cm original large scale paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Horizon Span | Original Large Scale Paintings Painting by Ritushka",
    "metaDescription": "Horizon Span, a 100×100cm original large scale art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/horizon-span.jpg",
    "alt": "Horizon Span, original large scale art on canvas by Ritushka, 100 by 100 centimetres",
    "mockups": [
      "horizon-span-in-coastal-home-43"
    ]
  },
  {
    "id": "aw-044",
    "slug": "field-light",
    "title": "Field Light",
    "year": 2026,
    "medium": "Acrylic with raw pigment on cotton canvas",
    "widthMm": 900,
    "heightMm": 1200,
    "widthCm": 90,
    "heightCm": 120,
    "palette": "warm sand, ochre and chalk",
    "collections": [
      "coastal-abstract-art",
      "abstract-landscapes"
    ],
    "primaryCollection": "coastal-abstract-art",
    "status": "available",
    "price": 14400,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Field Light belongs to Ritushka's Coastal Abstract Art series, an exploration of warm sand, ochre and chalk. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Field Light — 90 × 120cm original coastal abstract art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Field Light | Original Coastal Abstract Art Painting by Ritushka",
    "metaDescription": "Field Light, a 90×120cm original coastal abstract art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/field-light.jpg",
    "alt": "Field Light, original coastal abstract art on canvas by Ritushka, 90 by 120 centimetres",
    "mockups": [
      "field-light-in-modern-apartment-44"
    ]
  },
  {
    "id": "aw-045",
    "slug": "high-hush",
    "title": "High Hush",
    "year": 2023,
    "medium": "Acrylic, marble dust and pigment on linen",
    "widthMm": 2000,
    "heightMm": 1500,
    "widthCm": 200,
    "heightCm": 150,
    "palette": "indigo, teal and bleached coral",
    "collections": [
      "ocean-inspired-paintings",
      "coastal-abstract-art"
    ],
    "primaryCollection": "ocean-inspired-paintings",
    "status": "sold",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "High Hush belongs to Ritushka's Ocean Inspired Paintings series, an exploration of indigo, teal and bleached coral. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "High Hush — 200 × 150cm original ocean inspired paintings painting by Ritushka. Sold; commission a related work.",
    "seoTitle": "High Hush | Original Ocean Inspired Paintings Painting by Ritushka",
    "metaDescription": "High Hush, a 200×150cm original ocean inspired paintings by Sydney artist Ritushka. Sold — similar commissions available. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/high-hush.jpg",
    "alt": "High Hush, original ocean inspired paintings on canvas by Ritushka, 200 by 150 centimetres",
    "mockups": [
      "high-hush-in-architectural-interior-45"
    ]
  },
  {
    "id": "aw-046",
    "slug": "coastal-veil",
    "title": "Coastal Veil",
    "year": 2024,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 2400,
    "heightMm": 1200,
    "widthCm": 240,
    "heightCm": 120,
    "palette": "warm sand, ochre and chalk",
    "collections": [
      "contemporary-landscape-art",
      "textured-abstract-paintings"
    ],
    "primaryCollection": "contemporary-landscape-art",
    "status": "available",
    "price": 34400,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Coastal Veil belongs to Ritushka's Contemporary Landscape Art series, an exploration of warm sand, ochre and chalk. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Coastal Veil — 240 × 120cm original contemporary landscape art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Coastal Veil | Original Contemporary Landscape Art Painting by Ritushka",
    "metaDescription": "Coastal Veil, a 240×120cm original contemporary landscape art by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/coastal-veil.jpg",
    "alt": "Coastal Veil, original contemporary landscape art on canvas by Ritushka, 240 by 120 centimetres",
    "mockups": [
      "coastal-veil-in-commercial-space-46"
    ]
  },
  {
    "id": "aw-047",
    "slug": "estuary-verge",
    "title": "Estuary Verge",
    "year": 2025,
    "medium": "Mixed media and oil on deep-edge canvas",
    "widthMm": 1830,
    "heightMm": 1220,
    "widthCm": 183,
    "heightCm": 122,
    "palette": "indigo, teal and bleached coral",
    "collections": [
      "textured-abstract-paintings",
      "statement-artworks"
    ],
    "primaryCollection": "textured-abstract-paintings",
    "status": "available",
    "price": 27200,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Estuary Verge belongs to Ritushka's Textured Abstract Paintings series, an exploration of indigo, teal and bleached coral. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Estuary Verge — 183 × 122cm original textured abstract paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Estuary Verge | Original Textured Abstract Paintings Painting by Ritushka",
    "metaDescription": "Estuary Verge, a 183×122cm original textured abstract paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/estuary-verge.jpg",
    "alt": "Estuary Verge, original textured abstract paintings on canvas by Ritushka, 183 by 122 centimetres",
    "mockups": [
      "estuary-verge-in-designer-space-47"
    ]
  },
  {
    "id": "aw-048",
    "slug": "high-tide",
    "title": "High Tide",
    "year": 2026,
    "medium": "Oil and cold wax on canvas",
    "widthMm": 1830,
    "heightMm": 1830,
    "widthCm": 183,
    "heightCm": 183,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "blue-abstract-paintings",
      "large-scale-paintings"
    ],
    "primaryCollection": "blue-abstract-paintings",
    "status": "available",
    "price": 39600,
    "currency": "AUD",
    "orientation": "square",
    "story": "High Tide belongs to Ritushka's Blue Abstract Paintings series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "High Tide — 183 × 183cm original blue abstract paintings painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "High Tide | Original Blue Abstract Paintings Painting by Ritushka",
    "metaDescription": "High Tide, a 183×183cm original blue abstract paintings by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/high-tide.jpg",
    "alt": "High Tide, original blue abstract paintings on canvas by Ritushka, 183 by 183 centimetres",
    "mockups": [
      "high-tide-in-penthouse-48"
    ]
  },
  {
    "id": "aw-049",
    "slug": "headland-veil",
    "title": "Headland Veil",
    "year": 2023,
    "medium": "Mixed media and oil on deep-edge canvas",
    "widthMm": 900,
    "heightMm": 1200,
    "widthCm": 90,
    "heightCm": 120,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "modern-australian-art",
      "contemporary-landscape-art"
    ],
    "primaryCollection": "modern-australian-art",
    "status": "reserved",
    "price": 14400,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Headland Veil belongs to Ritushka's Modern Australian Art series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Headland Veil — 90 × 120cm original modern australian art painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Headland Veil | Original Modern Australian Art Painting by Ritushka",
    "metaDescription": "Headland Veil, a 90×120cm original modern australian art by Sydney artist Ritushka. Reserved. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/headland-veil.jpg",
    "alt": "Headland Veil, original modern australian art on canvas by Ritushka, 90 by 120 centimetres",
    "mockups": [
      "headland-veil-in-hotel-lobby-49"
    ]
  },
  {
    "id": "aw-050",
    "slug": "low-cadence",
    "title": "Low Cadence",
    "year": 2024,
    "medium": "Acrylic with raw pigment on cotton canvas",
    "widthMm": 900,
    "heightMm": 1200,
    "widthCm": 90,
    "heightCm": 120,
    "palette": "charcoal, fog and muted gold",
    "collections": [
      "statement-artworks",
      "modern-australian-art"
    ],
    "primaryCollection": "statement-artworks",
    "status": "available",
    "price": 14400,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Low Cadence belongs to Ritushka's Statement Artworks series, an exploration of charcoal, fog and muted gold. Built in translucent layers, the surface is worked back and rebuilt so light appears to move across it — a quality that rewards large walls and considered placement. The painting reads as a remembered place rather than a literal one, holding the calm and scale that collectors, interior designers and architects look for in contemporary abstract work.",
    "shortDescription": "Low Cadence — 90 × 120cm original statement artworks painting by Ritushka. Available now, shipped worldwide.",
    "seoTitle": "Low Cadence | Original Statement Artworks Painting by Ritushka",
    "metaDescription": "Low Cadence, a 90×120cm original statement artwork by Sydney artist Ritushka. Available now. Worldwide shipping & certificate of authenticity.",
    "image": "/artworks/low-cadence.jpg",
    "alt": "Low Cadence, original statement artwork on canvas by Ritushka, 90 by 120 centimetres",
    "mockups": [
      "low-cadence-in-boardroom-50"
    ]
  }
];
