// AUTO-GENERATED by scripts/build-real-artworks.mjs from the real Artwork folder.
import type { Artwork } from './types';
export const artworks: Artwork[] = [
  {
    "id": "aw-001",
    "slug": "approaching-destination",
    "title": "Approaching Destination",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1803,
    "palette": "deep teal, seafoam and warm sand",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Approaching Destination is an original painting by Ritushka — a swelling body of water breaking toward the shore, worked in deep teal, seafoam and warm sand. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Approaching Destination — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Approaching Destination | Original Painting by Ritushka",
    "metaDescription": "Approaching Destination, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. A swelling body of water breaking toward the shore. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/approaching-destination.jpg",
    "alt": "Approaching Destination — original abstract seascapes painting by Ritushka in deep teal, seafoam and warm sand",
    "mockups": [
      "approaching-destination-in-living-room"
    ]
  },
  {
    "id": "aw-002",
    "slug": "aqua-frost-thinking-of-you",
    "title": "Aqua Frost — Thinking of You",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1801,
    "imageHeight": 2400,
    "palette": "frosted aqua, silver and pale blue",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Aqua Frost — Thinking of You is an original painting by Ritushka — light scattering across a still, shallow surface, worked in frosted aqua, silver and pale blue. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Aqua Frost — Thinking of You — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Aqua Frost — Thinking of You | Original Painting by Ritushka",
    "metaDescription": "Aqua Frost — Thinking of You, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. Light scattering across a still, shallow surface. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/aqua-frost-thinking-of-you.jpg",
    "alt": "Aqua Frost — Thinking of You — original abstract seascapes painting by Ritushka in frosted aqua, silver and pale blue",
    "mockups": [
      "aqua-frost-thinking-of-you-in-luxury-home"
    ]
  },
  {
    "id": "aw-003",
    "slug": "blue-mountains",
    "title": "Blue Mountains",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2396,
    "imageHeight": 2400,
    "palette": "stone grey, mist blue and chalk white",
    "collections": [
      "abstract-landscapes",
      "contemporary-landscape-art",
      "modern-australian-art",
      "textured-abstract-paintings"
    ],
    "primaryCollection": "abstract-landscapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Blue Mountains is an original painting by Ritushka — ranges dissolving into cloud and distance, worked in stone grey, mist blue and chalk white. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Blue Mountains — an original abstract landscapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Blue Mountains | Original Painting by Ritushka",
    "metaDescription": "Blue Mountains, an original abstract landscapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. Ranges dissolving into cloud and distance. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/blue-mountains.jpg",
    "alt": "Blue Mountains — original abstract landscapes painting by Ritushka in stone grey, mist blue and chalk white",
    "mockups": [
      "blue-mountains-in-coastal-home"
    ]
  },
  {
    "id": "aw-004",
    "slug": "bush",
    "title": "Bush",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1854,
    "palette": "white and silver on deep black",
    "collections": [
      "other-works",
      "modern-australian-art"
    ],
    "primaryCollection": "other-works",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Bush is an original painting by Ritushka — native foliage drawn in white against darkness, worked in white and silver on deep black. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Bush — an original other works painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Bush | Original Painting by Ritushka",
    "metaDescription": "Bush, an original other works painting by Ritushka, contemporary artist in Lane Cove, Sydney. Native foliage drawn in white against darkness. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/bush.jpg",
    "alt": "Bush — original other works painting by Ritushka in white and silver on deep black",
    "mockups": [
      "bush-in-modern-apartment"
    ]
  },
  {
    "id": "aw-005",
    "slug": "coastal-waters",
    "title": "Coastal Waters",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 2397,
    "palette": "turquoise, jade and foam white",
    "collections": [
      "abstract-seascapes",
      "coastal-abstract-art",
      "ocean-inspired-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Coastal Waters is an original painting by Ritushka — the turning weight of a wave close to shore, worked in turquoise, jade and foam white. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Coastal Waters — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Coastal Waters | Original Painting by Ritushka",
    "metaDescription": "Coastal Waters, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. The turning weight of a wave close to shore. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/coastal-waters.jpg",
    "alt": "Coastal Waters — original abstract seascapes painting by Ritushka in turquoise, jade and foam white",
    "mockups": [
      "coastal-waters-in-architectural-interior"
    ]
  },
  {
    "id": "aw-006",
    "slug": "deliciousness",
    "title": "Deliciousness",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1842,
    "palette": "blush pink, coral and cream",
    "collections": [
      "statement-artworks",
      "textured-abstract-paintings"
    ],
    "primaryCollection": "statement-artworks",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Deliciousness is an original painting by Ritushka — a soft bloom of warmth and light, worked in blush pink, coral and cream. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Deliciousness — an original statement artworks painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Deliciousness | Original Painting by Ritushka",
    "metaDescription": "Deliciousness, an original statement artworks painting by Ritushka, contemporary artist in Lane Cove, Sydney. A soft bloom of warmth and light. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/deliciousness.jpg",
    "alt": "Deliciousness — original statement artworks painting by Ritushka in blush pink, coral and cream",
    "mockups": [
      "deliciousness-in-commercial-space"
    ]
  },
  {
    "id": "aw-007",
    "slug": "desire",
    "title": "Desire",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1801,
    "palette": "deep ocean blue, teal and breaking white",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings",
      "blue-abstract-paintings",
      "large-scale-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Desire is an original painting by Ritushka — a wave at the moment it begins to fold, worked in deep ocean blue, teal and breaking white. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Desire — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Desire | Original Painting by Ritushka",
    "metaDescription": "Desire, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. A wave at the moment it begins to fold. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/desire.jpg",
    "alt": "Desire — original abstract seascapes painting by Ritushka in deep ocean blue, teal and breaking white",
    "mockups": [
      "desire-in-designer-space"
    ]
  },
  {
    "id": "aw-008",
    "slug": "erruption",
    "title": "Erruption",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1802,
    "imageHeight": 2400,
    "palette": "rust, cloud white and lagoon blue",
    "collections": [
      "abstract-landscapes",
      "coastal-abstract-art",
      "contemporary-landscape-art"
    ],
    "primaryCollection": "abstract-landscapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Erruption is an original painting by Ritushka — a headland meeting bright shallow water, worked in rust, cloud white and lagoon blue. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Erruption — an original abstract landscapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Erruption | Original Painting by Ritushka",
    "metaDescription": "Erruption, an original abstract landscapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. A headland meeting bright shallow water. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/erruption.jpg",
    "alt": "Erruption — original abstract landscapes painting by Ritushka in rust, cloud white and lagoon blue",
    "mockups": [
      "erruption-in-penthouse"
    ]
  },
  {
    "id": "aw-009",
    "slug": "go-with-the-flow",
    "title": "Go With the Flow",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1927,
    "palette": "turquoise with jewelled brights",
    "collections": [
      "other-works"
    ],
    "primaryCollection": "other-works",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Go With the Flow is an original painting by Ritushka — a shoal of fish moving together as one, worked in turquoise with jewelled brights. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Go With the Flow — an original other works painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Go With the Flow | Original Painting by Ritushka",
    "metaDescription": "Go With the Flow, an original other works painting by Ritushka, contemporary artist in Lane Cove, Sydney. A shoal of fish moving together as one. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/go-with-the-flow.jpg",
    "alt": "Go With the Flow — original other works painting by Ritushka in turquoise with jewelled brights",
    "mockups": [
      "go-with-the-flow-in-hotel-lobby"
    ]
  },
  {
    "id": "aw-010",
    "slug": "horizon",
    "title": "Horizon",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1377,
    "palette": "warm grey, taupe and soft gold",
    "collections": [
      "abstract-landscapes",
      "contemporary-landscape-art",
      "large-scale-paintings"
    ],
    "primaryCollection": "abstract-landscapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Horizon is an original painting by Ritushka — a long, quiet horizon held in haze, worked in warm grey, taupe and soft gold. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Horizon — an original abstract landscapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Horizon | Original Painting by Ritushka",
    "metaDescription": "Horizon, an original abstract landscapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. A long, quiet horizon held in haze. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/horizon.jpg",
    "alt": "Horizon — original abstract landscapes painting by Ritushka in warm grey, taupe and soft gold",
    "mockups": [
      "horizon-in-boardroom"
    ]
  },
  {
    "id": "aw-011",
    "slug": "into-the-ever-blue",
    "title": "Into the Ever Blue",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2396,
    "imageHeight": 2400,
    "palette": "turquoise, ice white and slate",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Into the Ever Blue is an original painting by Ritushka — the pull of open water beyond the break, worked in turquoise, ice white and slate. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Into the Ever Blue — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Into the Ever Blue | Original Painting by Ritushka",
    "metaDescription": "Into the Ever Blue, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. The pull of open water beyond the break. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/into-the-ever-blue.jpg",
    "alt": "Into the Ever Blue — original abstract seascapes painting by Ritushka in turquoise, ice white and slate",
    "mockups": [
      "into-the-ever-blue-in-living-room"
    ]
  },
  {
    "id": "aw-012",
    "slug": "just-add-champagne",
    "title": "Just Add Champagne",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2384,
    "imageHeight": 2400,
    "palette": "rose, blush and pale gold",
    "collections": [
      "statement-artworks"
    ],
    "primaryCollection": "statement-artworks",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Just Add Champagne is an original painting by Ritushka — effervescence caught mid-rise, worked in rose, blush and pale gold. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Just Add Champagne — an original statement artworks painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Just Add Champagne | Original Painting by Ritushka",
    "metaDescription": "Just Add Champagne, an original statement artworks painting by Ritushka, contemporary artist in Lane Cove, Sydney. Effervescence caught mid-rise. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/just-add-champagne.jpg",
    "alt": "Just Add Champagne — original statement artworks painting by Ritushka in rose, blush and pale gold",
    "mockups": [
      "just-add-champagne-in-luxury-home"
    ]
  },
  {
    "id": "aw-013",
    "slug": "life-chooses-you",
    "title": "Life Chooses You",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2396,
    "imageHeight": 2400,
    "palette": "cream, umber and weathered white",
    "collections": [
      "textured-abstract-paintings",
      "contemporary-landscape-art"
    ],
    "primaryCollection": "textured-abstract-paintings",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Life Chooses You is an original painting by Ritushka — a worked surface of drift and sediment, worked in cream, umber and weathered white. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Life Chooses You — an original textured abstract paintings painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Life Chooses You | Original Painting by Ritushka",
    "metaDescription": "Life Chooses You, an original textured abstract paintings painting by Ritushka, contemporary artist in Lane Cove, Sydney. A worked surface of drift and sediment. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/life-chooses-you.jpg",
    "alt": "Life Chooses You — original textured abstract paintings painting by Ritushka in cream, umber and weathered white",
    "mockups": [
      "life-chooses-you-in-coastal-home"
    ]
  },
  {
    "id": "aw-014",
    "slug": "mashmellow",
    "title": "Mashmellow",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 2364,
    "palette": "butter cream, sand and pale rose",
    "collections": [
      "statement-artworks",
      "textured-abstract-paintings"
    ],
    "primaryCollection": "statement-artworks",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Mashmellow is an original painting by Ritushka — warmth settling into softness, worked in butter cream, sand and pale rose. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Mashmellow — an original statement artworks painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Mashmellow | Original Painting by Ritushka",
    "metaDescription": "Mashmellow, an original statement artworks painting by Ritushka, contemporary artist in Lane Cove, Sydney. Warmth settling into softness. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/mashmellow.jpg",
    "alt": "Mashmellow — original statement artworks painting by Ritushka in butter cream, sand and pale rose",
    "mockups": [
      "mashmellow-in-modern-apartment"
    ]
  },
  {
    "id": "aw-015",
    "slug": "numero-uno",
    "title": "Numero Uno",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1924,
    "imageHeight": 2400,
    "palette": "white and pearl on black",
    "collections": [
      "other-works"
    ],
    "primaryCollection": "other-works",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Numero Uno is an original painting by Ritushka — repeated forms in ordered rhythm, worked in white and pearl on black. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Numero Uno — an original other works painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Numero Uno | Original Painting by Ritushka",
    "metaDescription": "Numero Uno, an original other works painting by Ritushka, contemporary artist in Lane Cove, Sydney. Repeated forms in ordered rhythm. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/numero-uno.jpg",
    "alt": "Numero Uno — original other works painting by Ritushka in white and pearl on black",
    "mockups": [
      "numero-uno-in-architectural-interior"
    ]
  },
  {
    "id": "aw-016",
    "slug": "one-of-a-kind",
    "title": "One of a Kind",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1617,
    "imageHeight": 2400,
    "palette": "deep teal, ink blue and mast white",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings",
      "coastal-abstract-art"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "One of a Kind is an original painting by Ritushka — sails held on dark, glassy water, worked in deep teal, ink blue and mast white. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "One of a Kind — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "One of a Kind | Original Painting by Ritushka",
    "metaDescription": "One of a Kind, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. Sails held on dark, glassy water. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/one-of-a-kind.jpg",
    "alt": "One of a Kind — original abstract seascapes painting by Ritushka in deep teal, ink blue and mast white",
    "mockups": [
      "one-of-a-kind-in-commercial-space"
    ]
  },
  {
    "id": "aw-017",
    "slug": "paragliding",
    "title": "Paragliding",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1668,
    "imageHeight": 2400,
    "palette": "earth brown, teal and bone",
    "collections": [
      "textured-abstract-paintings",
      "contemporary-landscape-art"
    ],
    "primaryCollection": "textured-abstract-paintings",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Paragliding is an original painting by Ritushka — the ground seen from a lifting height, worked in earth brown, teal and bone. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Paragliding — an original textured abstract paintings painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Paragliding | Original Painting by Ritushka",
    "metaDescription": "Paragliding, an original textured abstract paintings painting by Ritushka, contemporary artist in Lane Cove, Sydney. The ground seen from a lifting height. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/paragliding.jpg",
    "alt": "Paragliding — original textured abstract paintings painting by Ritushka in earth brown, teal and bone",
    "mockups": [
      "paragliding-in-designer-space"
    ]
  },
  {
    "id": "aw-018",
    "slug": "peony-thinking-of-me",
    "title": "Peony — Thinking of Me",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1790,
    "imageHeight": 2400,
    "palette": "cream, blush and soft apricot",
    "collections": [
      "statement-artworks"
    ],
    "primaryCollection": "statement-artworks",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Peony — Thinking of Me is an original painting by Ritushka — a petal-light field of warmth, worked in cream, blush and soft apricot. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Peony — Thinking of Me — an original statement artworks painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Peony — Thinking of Me | Original Painting by Ritushka",
    "metaDescription": "Peony — Thinking of Me, an original statement artworks painting by Ritushka, contemporary artist in Lane Cove, Sydney. A petal-light field of warmth. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/peony-thinking-of-me.jpg",
    "alt": "Peony — Thinking of Me — original statement artworks painting by Ritushka in cream, blush and soft apricot",
    "mockups": [
      "peony-thinking-of-me-in-penthouse"
    ]
  },
  {
    "id": "aw-019",
    "slug": "piece-of-white-heavan",
    "title": "Piece of White Heaven",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 2398,
    "palette": "sky blue, cloud white and aqua",
    "collections": [
      "abstract-landscapes",
      "abstract-seascapes",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "abstract-landscapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Piece of White Heaven is an original painting by Ritushka — clouds breaking over open water, worked in sky blue, cloud white and aqua. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Piece of White Heaven — an original abstract landscapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Piece of White Heaven | Original Painting by Ritushka",
    "metaDescription": "Piece of White Heaven, an original abstract landscapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. Clouds breaking over open water. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/piece-of-white-heavan.jpg",
    "alt": "Piece of White Heaven — original abstract landscapes painting by Ritushka in sky blue, cloud white and aqua",
    "mockups": [
      "piece-of-white-heavan-in-hotel-lobby"
    ]
  },
  {
    "id": "aw-020",
    "slug": "plateau",
    "title": "Plateau",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1596,
    "palette": "bone, oyster and pale sand",
    "collections": [
      "abstract-landscapes",
      "contemporary-landscape-art",
      "large-scale-paintings"
    ],
    "primaryCollection": "abstract-landscapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Plateau is an original painting by Ritushka — a wide, still expanse under flat light, worked in bone, oyster and pale sand. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Plateau — an original abstract landscapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Plateau | Original Painting by Ritushka",
    "metaDescription": "Plateau, an original abstract landscapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. A wide, still expanse under flat light. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/plateau.jpg",
    "alt": "Plateau — original abstract landscapes painting by Ritushka in bone, oyster and pale sand",
    "mockups": [
      "plateau-in-boardroom"
    ]
  },
  {
    "id": "aw-021",
    "slug": "reflection",
    "title": "Reflection",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 2396,
    "palette": "cobalt, ultramarine and white",
    "collections": [
      "other-works",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "other-works",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Reflection is an original painting by Ritushka — light scattered in circles across deep blue, worked in cobalt, ultramarine and white. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Reflection — an original other works painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Reflection | Original Painting by Ritushka",
    "metaDescription": "Reflection, an original other works painting by Ritushka, contemporary artist in Lane Cove, Sydney. Light scattered in circles across deep blue. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/reflection.jpg",
    "alt": "Reflection — original other works painting by Ritushka in cobalt, ultramarine and white",
    "mockups": [
      "reflection-in-living-room"
    ]
  },
  {
    "id": "aw-022",
    "slug": "river-of-my-thoughts",
    "title": "River of My Thoughts",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1801,
    "palette": "pearl, russet and soft grey",
    "collections": [
      "textured-abstract-paintings",
      "contemporary-landscape-art"
    ],
    "primaryCollection": "textured-abstract-paintings",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "River of My Thoughts is an original painting by Ritushka — a current of drifting, layered marks, worked in pearl, russet and soft grey. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "River of My Thoughts — an original textured abstract paintings painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "River of My Thoughts | Original Painting by Ritushka",
    "metaDescription": "River of My Thoughts, an original textured abstract paintings painting by Ritushka, contemporary artist in Lane Cove, Sydney. A current of drifting, layered marks. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/river-of-my-thoughts.jpg",
    "alt": "River of My Thoughts — original textured abstract paintings painting by Ritushka in pearl, russet and soft grey",
    "mockups": [
      "river-of-my-thoughts-in-luxury-home"
    ]
  },
  {
    "id": "aw-023",
    "slug": "rushing-shallows",
    "title": "Rushing Shallows",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 2400,
    "palette": "bone white, stone and pale aqua",
    "collections": [
      "coastal-abstract-art",
      "abstract-seascapes",
      "ocean-inspired-paintings"
    ],
    "primaryCollection": "coastal-abstract-art",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Rushing Shallows is an original painting by Ritushka — water racing over rock and sand, worked in bone white, stone and pale aqua. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Rushing Shallows — an original coastal abstract art painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Rushing Shallows | Original Painting by Ritushka",
    "metaDescription": "Rushing Shallows, an original coastal abstract art painting by Ritushka, contemporary artist in Lane Cove, Sydney. Water racing over rock and sand. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/rushing-shallows.jpg",
    "alt": "Rushing Shallows — original coastal abstract art painting by Ritushka in bone white, stone and pale aqua",
    "mockups": [
      "rushing-shallows-in-coastal-home"
    ]
  },
  {
    "id": "aw-024",
    "slug": "set-sail",
    "title": "Set Sail",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 2348,
    "palette": "deep sea blue, teal and white",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Set Sail is an original painting by Ritushka — sails against a darkening harbour, worked in deep sea blue, teal and white. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Set Sail — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Set Sail | Original Painting by Ritushka",
    "metaDescription": "Set Sail, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. Sails against a darkening harbour. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/set-sail.jpg",
    "alt": "Set Sail — original abstract seascapes painting by Ritushka in deep sea blue, teal and white",
    "mockups": [
      "set-sail-in-modern-apartment"
    ]
  },
  {
    "id": "aw-025",
    "slug": "shoreham",
    "title": "Shoreham",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2395,
    "imageHeight": 2400,
    "palette": "sky blue, cloud white and warm dune",
    "collections": [
      "coastal-abstract-art",
      "abstract-landscapes",
      "modern-australian-art"
    ],
    "primaryCollection": "coastal-abstract-art",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Shoreham is an original painting by Ritushka — a dune rising under a wide coastal sky, worked in sky blue, cloud white and warm dune. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Shoreham — an original coastal abstract art painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Shoreham | Original Painting by Ritushka",
    "metaDescription": "Shoreham, an original coastal abstract art painting by Ritushka, contemporary artist in Lane Cove, Sydney. A dune rising under a wide coastal sky. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/shoreham.jpg",
    "alt": "Shoreham — original coastal abstract art painting by Ritushka in sky blue, cloud white and warm dune",
    "mockups": [
      "shoreham-in-architectural-interior"
    ]
  },
  {
    "id": "aw-026",
    "slug": "soft-awakening",
    "title": "Soft Awakening",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 2400,
    "palette": "pale aqua, mist and cream",
    "collections": [
      "abstract-seascapes",
      "statement-artworks"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Soft Awakening is an original painting by Ritushka — first light spreading across still water, worked in pale aqua, mist and cream. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Soft Awakening — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Soft Awakening | Original Painting by Ritushka",
    "metaDescription": "Soft Awakening, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. First light spreading across still water. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/soft-awakening.jpg",
    "alt": "Soft Awakening — original abstract seascapes painting by Ritushka in pale aqua, mist and cream",
    "mockups": [
      "soft-awakening-in-commercial-space"
    ]
  },
  {
    "id": "aw-027",
    "slug": "softly-loving-dreamscape",
    "title": "Softly Loving Dreamscape",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1455,
    "imageHeight": 2400,
    "palette": "turquoise, deep teal and foam",
    "collections": [
      "ocean-inspired-paintings",
      "blue-abstract-paintings",
      "abstract-seascapes",
      "large-scale-paintings"
    ],
    "primaryCollection": "ocean-inspired-paintings",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Softly Loving Dreamscape is an original painting by Ritushka — looking down through clear, moving water, worked in turquoise, deep teal and foam. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Softly Loving Dreamscape — an original ocean inspired paintings painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Softly Loving Dreamscape | Original Painting by Ritushka",
    "metaDescription": "Softly Loving Dreamscape, an original ocean inspired paintings painting by Ritushka, contemporary artist in Lane Cove, Sydney. Looking down through clear, moving water. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/softly-loving-dreamscape.jpg",
    "alt": "Softly Loving Dreamscape — original ocean inspired paintings painting by Ritushka in turquoise, deep teal and foam",
    "mockups": [
      "softly-loving-dreamscape-in-designer-space"
    ]
  },
  {
    "id": "aw-028",
    "slug": "stillness",
    "title": "Stillness",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 2369,
    "palette": "cobalt, aqua and warm sand",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Stillness is an original painting by Ritushka — banded sea and sky at rest, worked in cobalt, aqua and warm sand. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Stillness — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Stillness | Original Painting by Ritushka",
    "metaDescription": "Stillness, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. Banded sea and sky at rest. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/stillness.jpg",
    "alt": "Stillness — original abstract seascapes painting by Ritushka in cobalt, aqua and warm sand",
    "mockups": [
      "stillness-in-penthouse"
    ]
  },
  {
    "id": "aw-029",
    "slug": "strangely-attracted-to-you",
    "title": "Strangely Attracted to You",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1990,
    "palette": "rose, crimson and cream",
    "collections": [
      "statement-artworks",
      "textured-abstract-paintings",
      "large-scale-paintings"
    ],
    "primaryCollection": "statement-artworks",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Strangely Attracted to You is an original painting by Ritushka — a charged field of colour and mark, worked in rose, crimson and cream. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Strangely Attracted to You — an original statement artworks painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Strangely Attracted to You | Original Painting by Ritushka",
    "metaDescription": "Strangely Attracted to You, an original statement artworks painting by Ritushka, contemporary artist in Lane Cove, Sydney. A charged field of colour and mark. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/strangely-attracted-to-you.jpg",
    "alt": "Strangely Attracted to You — original statement artworks painting by Ritushka in rose, crimson and cream",
    "mockups": [
      "strangely-attracted-to-you-in-hotel-lobby"
    ]
  },
  {
    "id": "aw-030",
    "slug": "sunrise-over-tokyo",
    "title": "Sunrise Over Tokyo",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 2393,
    "palette": "coral, flame orange and rose",
    "collections": [
      "statement-artworks",
      "contemporary-landscape-art"
    ],
    "primaryCollection": "statement-artworks",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Sunrise Over Tokyo is an original painting by Ritushka — a city sky at the moment of sunrise, worked in coral, flame orange and rose. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Sunrise Over Tokyo — an original statement artworks painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Sunrise Over Tokyo | Original Painting by Ritushka",
    "metaDescription": "Sunrise Over Tokyo, an original statement artworks painting by Ritushka, contemporary artist in Lane Cove, Sydney. A city sky at the moment of sunrise. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/sunrise-over-tokyo.jpg",
    "alt": "Sunrise Over Tokyo — original statement artworks painting by Ritushka in coral, flame orange and rose",
    "mockups": [
      "sunrise-over-tokyo-in-boardroom"
    ]
  },
  {
    "id": "aw-031",
    "slug": "the-apostles",
    "title": "The Apostles",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1798,
    "palette": "sea green, storm grey and ochre stone",
    "collections": [
      "coastal-abstract-art",
      "abstract-landscapes",
      "modern-australian-art"
    ],
    "primaryCollection": "coastal-abstract-art",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "The Apostles is an original painting by Ritushka — sea stacks standing in restless water, worked in sea green, storm grey and ochre stone. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "The Apostles — an original coastal abstract art painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "The Apostles | Original Painting by Ritushka",
    "metaDescription": "The Apostles, an original coastal abstract art painting by Ritushka, contemporary artist in Lane Cove, Sydney. Sea stacks standing in restless water. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/the-apostles.jpg",
    "alt": "The Apostles — original coastal abstract art painting by Ritushka in sea green, storm grey and ochre stone",
    "mockups": [
      "the-apostles-in-living-room"
    ]
  },
  {
    "id": "aw-032",
    "slug": "the-world-in-my-eyes-2",
    "title": "The World In My Eyes II",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1604,
    "imageHeight": 2400,
    "palette": "saturated orange, blue and teal",
    "collections": [
      "other-works"
    ],
    "primaryCollection": "other-works",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "The World In My Eyes II is an original painting by Ritushka — an eye opening into pattern and colour, worked in saturated orange, blue and teal. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "The World In My Eyes II — an original other works painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "The World In My Eyes II | Original Painting by Ritushka",
    "metaDescription": "The World In My Eyes II, an original other works painting by Ritushka, contemporary artist in Lane Cove, Sydney. An eye opening into pattern and colour. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/the-world-in-my-eyes-2.jpg",
    "alt": "The World In My Eyes II — original other works painting by Ritushka in saturated orange, blue and teal",
    "mockups": [
      "the-world-in-my-eyes-2-in-luxury-home"
    ]
  },
  {
    "id": "aw-033",
    "slug": "the-world-in-my-eyes",
    "title": "The World In My Eyes",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1608,
    "imageHeight": 2400,
    "palette": "saturated blue, red and gold",
    "collections": [
      "other-works"
    ],
    "primaryCollection": "other-works",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "The World In My Eyes is an original painting by Ritushka — a figure rendered in bold graphic colour, worked in saturated blue, red and gold. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "The World In My Eyes — an original other works painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "The World In My Eyes | Original Painting by Ritushka",
    "metaDescription": "The World In My Eyes, an original other works painting by Ritushka, contemporary artist in Lane Cove, Sydney. A figure rendered in bold graphic colour. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/the-world-in-my-eyes.jpg",
    "alt": "The World In My Eyes — original other works painting by Ritushka in saturated blue, red and gold",
    "mockups": [
      "the-world-in-my-eyes-in-coastal-home"
    ]
  },
  {
    "id": "aw-034",
    "slug": "tree-of-our-life",
    "title": "Tree of Our Life",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1607,
    "palette": "turquoise, blush and jewelled brights",
    "collections": [
      "other-works"
    ],
    "primaryCollection": "other-works",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Tree of Our Life is an original painting by Ritushka — a tree alive with birds, flowers and detail, worked in turquoise, blush and jewelled brights. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Tree of Our Life — an original other works painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Tree of Our Life | Original Painting by Ritushka",
    "metaDescription": "Tree of Our Life, an original other works painting by Ritushka, contemporary artist in Lane Cove, Sydney. A tree alive with birds, flowers and detail. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/tree-of-our-life.jpg",
    "alt": "Tree of Our Life — original other works painting by Ritushka in turquoise, blush and jewelled brights",
    "mockups": [
      "tree-of-our-life-in-modern-apartment"
    ]
  },
  {
    "id": "aw-035",
    "slug": "turbulence",
    "title": "Turbulence",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2360,
    "imageHeight": 2400,
    "palette": "pale blue, cloud white and aqua",
    "collections": [
      "abstract-seascapes",
      "abstract-landscapes",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Turbulence is an original painting by Ritushka — weather gathering over open water, worked in pale blue, cloud white and aqua. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Turbulence — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Turbulence | Original Painting by Ritushka",
    "metaDescription": "Turbulence, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. Weather gathering over open water. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/turbulence.jpg",
    "alt": "Turbulence — original abstract seascapes painting by Ritushka in pale blue, cloud white and aqua",
    "mockups": [
      "turbulence-in-architectural-interior"
    ]
  },
  {
    "id": "aw-036",
    "slug": "turquoise-tuesday",
    "title": "Turquoise Tuesday",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 2393,
    "palette": "turquoise, surf white and soft sky",
    "collections": [
      "abstract-seascapes",
      "coastal-abstract-art",
      "ocean-inspired-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "square",
    "story": "Turquoise Tuesday is an original painting by Ritushka — a bright day of moving surf, worked in turquoise, surf white and soft sky. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Turquoise Tuesday — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Turquoise Tuesday | Original Painting by Ritushka",
    "metaDescription": "Turquoise Tuesday, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. A bright day of moving surf. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/turquoise-tuesday.jpg",
    "alt": "Turquoise Tuesday — original abstract seascapes painting by Ritushka in turquoise, surf white and soft sky",
    "mockups": [
      "turquoise-tuesday-in-commercial-space"
    ]
  },
  {
    "id": "aw-037",
    "slug": "urban-jungle",
    "title": "Urban Jungle",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1787,
    "imageHeight": 2400,
    "palette": "pale grey, aqua and silver",
    "collections": [
      "textured-abstract-paintings",
      "other-works"
    ],
    "primaryCollection": "textured-abstract-paintings",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Urban Jungle is an original painting by Ritushka — pattern emerging through a worked surface, worked in pale grey, aqua and silver. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Urban Jungle — an original textured abstract paintings painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Urban Jungle | Original Painting by Ritushka",
    "metaDescription": "Urban Jungle, an original textured abstract paintings painting by Ritushka, contemporary artist in Lane Cove, Sydney. Pattern emerging through a worked surface. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/urban-jungle.jpg",
    "alt": "Urban Jungle — original textured abstract paintings painting by Ritushka in pale grey, aqua and silver",
    "mockups": [
      "urban-jungle-in-designer-space"
    ]
  },
  {
    "id": "aw-038",
    "slug": "without-sweet-harmony-2",
    "title": "Without Sweet Harmony II",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1614,
    "imageHeight": 2400,
    "palette": "scarlet, orange and deep rose",
    "collections": [
      "statement-artworks"
    ],
    "primaryCollection": "statement-artworks",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Without Sweet Harmony II is an original painting by Ritushka — a second movement in fire and rose, worked in scarlet, orange and deep rose. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Without Sweet Harmony II — an original statement artworks painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Without Sweet Harmony II | Original Painting by Ritushka",
    "metaDescription": "Without Sweet Harmony II, an original statement artworks painting by Ritushka, contemporary artist in Lane Cove, Sydney. A second movement in fire and rose. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/without-sweet-harmony-2.jpg",
    "alt": "Without Sweet Harmony II — original statement artworks painting by Ritushka in scarlet, orange and deep rose",
    "mockups": [
      "without-sweet-harmony-2-in-penthouse"
    ]
  },
  {
    "id": "aw-039",
    "slug": "without-sweet-harmony",
    "title": "Without Sweet Harmony",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 1628,
    "imageHeight": 2400,
    "palette": "flame orange, crimson and rose",
    "collections": [
      "statement-artworks"
    ],
    "primaryCollection": "statement-artworks",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "portrait",
    "story": "Without Sweet Harmony is an original painting by Ritushka — heat and movement in full colour, worked in flame orange, crimson and rose. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Without Sweet Harmony — an original statement artworks painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Without Sweet Harmony | Original Painting by Ritushka",
    "metaDescription": "Without Sweet Harmony, an original statement artworks painting by Ritushka, contemporary artist in Lane Cove, Sydney. Heat and movement in full colour. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/without-sweet-harmony.jpg",
    "alt": "Without Sweet Harmony — original statement artworks painting by Ritushka in flame orange, crimson and rose",
    "mockups": [
      "without-sweet-harmony-in-hotel-lobby"
    ]
  },
  {
    "id": "aw-040",
    "slug": "wave",
    "title": "Wave",
    "year": null,
    "medium": "",
    "widthCm": null,
    "heightCm": null,
    "imageWidth": 2400,
    "imageHeight": 1817,
    "palette": "turquoise, deep blue and foam white",
    "collections": [
      "abstract-seascapes",
      "ocean-inspired-paintings",
      "blue-abstract-paintings"
    ],
    "primaryCollection": "abstract-seascapes",
    "status": "enquire",
    "price": null,
    "currency": "AUD",
    "orientation": "landscape",
    "story": "Wave is an original painting by Ritushka — the curl and break of a single wave, worked in turquoise, deep blue and foam white. Built in layers from her Lane Cove studio in Sydney, the surface is developed and reworked so that light seems to shift across it as you move. Dimensions, medium and price for this work are available on request.",
    "shortDescription": "Wave — an original abstract seascapes painting by Sydney artist Ritushka. Enquire for dimensions, medium and price.",
    "seoTitle": "Wave | Original Painting by Ritushka",
    "metaDescription": "Wave, an original abstract seascapes painting by Ritushka, contemporary artist in Lane Cove, Sydney. The curl and break of a single wave. Enquire for size, medium and price. Ships worldwide.",
    "image": "/artworks/wave.jpg",
    "alt": "Wave — original abstract seascapes painting by Ritushka in turquoise, deep blue and foam white",
    "mockups": [
      "wave-in-boardroom"
    ]
  }
];
