// AUTO-GENERATED by scripts/generate-data.mjs — edit the generator or override per-record, do not hand-edit blindly.
import type { Collection } from './types';
export const collections: Collection[] = [
  {
    "id": "col-01",
    "slug": "abstract-landscapes",
    "name": "Abstract Landscapes",
    "keyword": "abstract landscape art",
    "intent": "collectors seeking contemporary abstract landscape paintings",
    "heading": "Abstract Landscapes by Ritushka",
    "seoTitle": "Abstract Landscapes | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore abstract landscapes by Ritushka — original abstract landscape art for collectors seeking contemporary abstract landscape paintings. Sydney-based contemporary artist shipping worldwide. Available works and commissions.",
    "intro": "This collection brings together Ritushka's abstract landscapes — original abstract landscape art created for collectors seeking contemporary abstract landscape paintings. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity.",
    "faqs": [
      {
        "q": "What sizes do abstract landscapes come in?",
        "a": "Works range from intimate pieces to large-scale statement paintings over two metres. Custom sizes are available by commission."
      },
      {
        "q": "Can I commission a piece from the abstract landscapes collection in a specific palette?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks plus shipping."
      },
      {
        "q": "Do you ship abstract landscapes internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-02",
    "slug": "abstract-seascapes",
    "name": "Abstract Seascapes",
    "keyword": "abstract seascape paintings",
    "intent": "buyers of coastal and ocean abstract art",
    "heading": "Abstract Seascapes by Ritushka",
    "seoTitle": "Abstract Seascapes | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore abstract seascapes by Ritushka — original abstract seascape paintings for buyers of coastal and ocean abstract art. Sydney-based contemporary artist shipping worldwide. Available works and commissions.",
    "intro": "This collection brings together Ritushka's abstract seascapes — original abstract seascape paintings created for buyers of coastal and ocean abstract art. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity.",
    "faqs": [
      {
        "q": "What sizes do abstract seascapes come in?",
        "a": "Works range from intimate pieces to large-scale statement paintings over two metres. Custom sizes are available by commission."
      },
      {
        "q": "Can I commission a piece from the abstract seascapes collection in a specific palette?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks plus shipping."
      },
      {
        "q": "Do you ship abstract seascapes internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-03",
    "slug": "large-scale-paintings",
    "name": "Large Scale Paintings",
    "keyword": "large scale art",
    "intent": "designers and architects sourcing oversized statement works",
    "heading": "Large Scale Paintings by Ritushka",
    "seoTitle": "Large Scale Paintings | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore large scale paintings by Ritushka — original large scale art for designers and architects sourcing oversized statement works. Sydney-based contemporary artist shipping worldwide. Available works and commissions.",
    "intro": "This collection brings together Ritushka's large scale paintings — original large scale art created for designers and architects sourcing oversized statement works. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity.",
    "faqs": [
      {
        "q": "What sizes do large scale paintings come in?",
        "a": "Works range from intimate pieces to large-scale statement paintings over two metres. Custom sizes are available by commission."
      },
      {
        "q": "Can I commission a piece from the large scale paintings collection in a specific palette?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks plus shipping."
      },
      {
        "q": "Do you ship large scale paintings internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-04",
    "slug": "coastal-abstract-art",
    "name": "Coastal Abstract Art",
    "keyword": "coastal abstract art",
    "intent": "luxury coastal home owners",
    "heading": "Coastal Abstract Art by Ritushka",
    "seoTitle": "Coastal Abstract Art | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore coastal abstract art by Ritushka — original coastal abstract art for luxury coastal home owners. Sydney-based contemporary artist shipping worldwide. Available works and commissions.",
    "intro": "This collection brings together Ritushka's coastal abstract art — original coastal abstract art created for luxury coastal home owners. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity.",
    "faqs": [
      {
        "q": "What sizes do coastal abstract art come in?",
        "a": "Works range from intimate pieces to large-scale statement paintings over two metres. Custom sizes are available by commission."
      },
      {
        "q": "Can I commission a piece from the coastal abstract art collection in a specific palette?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks plus shipping."
      },
      {
        "q": "Do you ship coastal abstract art internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-05",
    "slug": "ocean-inspired-paintings",
    "name": "Ocean Inspired Paintings",
    "keyword": "ocean inspired paintings",
    "intent": "collectors drawn to the sea",
    "heading": "Ocean Inspired Paintings by Ritushka",
    "seoTitle": "Ocean Inspired Paintings | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore ocean inspired paintings by Ritushka — original ocean inspired paintings for collectors drawn to the sea. Sydney-based contemporary artist shipping worldwide. Available works and commissions.",
    "intro": "This collection brings together Ritushka's ocean inspired paintings — original ocean inspired paintings created for collectors drawn to the sea. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity.",
    "faqs": [
      {
        "q": "What sizes do ocean inspired paintings come in?",
        "a": "Works range from intimate pieces to large-scale statement paintings over two metres. Custom sizes are available by commission."
      },
      {
        "q": "Can I commission a piece from the ocean inspired paintings collection in a specific palette?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks plus shipping."
      },
      {
        "q": "Do you ship ocean inspired paintings internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-06",
    "slug": "contemporary-landscape-art",
    "name": "Contemporary Landscape Art",
    "keyword": "contemporary landscape art",
    "intent": "modern interiors",
    "heading": "Contemporary Landscape Art by Ritushka",
    "seoTitle": "Contemporary Landscape Art | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore contemporary landscape art by Ritushka — original contemporary landscape art for modern interiors. Sydney-based contemporary artist shipping worldwide. Available works and commissions.",
    "intro": "This collection brings together Ritushka's contemporary landscape art — original contemporary landscape art created for modern interiors. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity.",
    "faqs": [
      {
        "q": "What sizes do contemporary landscape art come in?",
        "a": "Works range from intimate pieces to large-scale statement paintings over two metres. Custom sizes are available by commission."
      },
      {
        "q": "Can I commission a piece from the contemporary landscape art collection in a specific palette?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks plus shipping."
      },
      {
        "q": "Do you ship contemporary landscape art internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-07",
    "slug": "textured-abstract-paintings",
    "name": "Textured Abstract Paintings",
    "keyword": "textured abstract paintings",
    "intent": "collectors who value materiality and impasto",
    "heading": "Textured Abstract Paintings by Ritushka",
    "seoTitle": "Textured Abstract Paintings | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore textured abstract paintings by Ritushka — original textured abstract paintings for collectors who value materiality and impasto. Sydney-based contemporary artist shipping worldwide. Available works and commissions.",
    "intro": "This collection brings together Ritushka's textured abstract paintings — original textured abstract paintings created for collectors who value materiality and impasto. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity.",
    "faqs": [
      {
        "q": "What sizes do textured abstract paintings come in?",
        "a": "Works range from intimate pieces to large-scale statement paintings over two metres. Custom sizes are available by commission."
      },
      {
        "q": "Can I commission a piece from the textured abstract paintings collection in a specific palette?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks plus shipping."
      },
      {
        "q": "Do you ship textured abstract paintings internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-08",
    "slug": "blue-abstract-paintings",
    "name": "Blue Abstract Paintings",
    "keyword": "blue abstract paintings",
    "intent": "colour-led buyers",
    "heading": "Blue Abstract Paintings by Ritushka",
    "seoTitle": "Blue Abstract Paintings | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore blue abstract paintings by Ritushka — original blue abstract paintings for colour-led buyers. Sydney-based contemporary artist shipping worldwide. Available works and commissions.",
    "intro": "This collection brings together Ritushka's blue abstract paintings — original blue abstract paintings created for colour-led buyers. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity.",
    "faqs": [
      {
        "q": "What sizes do blue abstract paintings come in?",
        "a": "Works range from intimate pieces to large-scale statement paintings over two metres. Custom sizes are available by commission."
      },
      {
        "q": "Can I commission a piece from the blue abstract paintings collection in a specific palette?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks plus shipping."
      },
      {
        "q": "Do you ship blue abstract paintings internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-09",
    "slug": "modern-australian-art",
    "name": "Modern Australian Art",
    "keyword": "modern australian art",
    "intent": "buyers seeking Australian provenance",
    "heading": "Modern Australian Art by Ritushka",
    "seoTitle": "Modern Australian Art | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore modern australian art by Ritushka — original modern australian art for buyers seeking Australian provenance. Sydney-based contemporary artist shipping worldwide. Available works and commissions.",
    "intro": "This collection brings together Ritushka's modern australian art — original modern australian art created for buyers seeking Australian provenance. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity.",
    "faqs": [
      {
        "q": "What sizes do modern australian art come in?",
        "a": "Works range from intimate pieces to large-scale statement paintings over two metres. Custom sizes are available by commission."
      },
      {
        "q": "Can I commission a piece from the modern australian art collection in a specific palette?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks plus shipping."
      },
      {
        "q": "Do you ship modern australian art internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-10",
    "slug": "statement-artworks",
    "name": "Statement Artworks",
    "keyword": "statement artwork",
    "intent": "corporate and luxury commissions",
    "heading": "Statement Artworks by Ritushka",
    "seoTitle": "Statement Artworks | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore statement artworks by Ritushka — original statement artwork for corporate and luxury commissions. Sydney-based contemporary artist shipping worldwide. Available works and commissions.",
    "intro": "This collection brings together Ritushka's statement artworks — original statement artwork created for corporate and luxury commissions. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity.",
    "faqs": [
      {
        "q": "What sizes do statement artworks come in?",
        "a": "Works range from intimate pieces to large-scale statement paintings over two metres. Custom sizes are available by commission."
      },
      {
        "q": "Can I commission a piece from the statement artworks collection in a specific palette?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks plus shipping."
      },
      {
        "q": "Do you ship statement artworks internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  }
];
