// AUTO-GENERATED by scripts/sync-register.py from "Artwork Records.ods".
import type { Collection } from './types';
export const collections: Collection[] = [
  {
    "id": "col-01",
    "slug": "abstract-landscapes",
    "name": "Abstract Landscapes",
    "keyword": "abstract landscape art",
    "intent": "collectors seeking contemporary abstract landscape paintings",
    "heading": "Abstract Landscapes by Ritushka",
    "seoTitle": "Abstract Landscapes | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore abstract landscapes by Ritushka — original abstract landscape art for collectors seeking contemporary abstract landscape paintings. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's abstract landscapes — original abstract landscape art created for collectors seeking contemporary abstract landscape paintings. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 60 × 60 cm to 100 × 150 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these abstract landscapes come in?",
        "a": "This collection ranges from 60 × 60 cm to 100 × 150 cm — Blue Mountains is the most intimate and Plateau the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 7 works available in this collection."
      },
      {
        "q": "How much do abstract landscapes cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-02",
    "slug": "abstract-seascapes",
    "name": "Abstract Seascapes",
    "keyword": "abstract seascape paintings",
    "intent": "buyers of coastal and ocean abstract art",
    "heading": "Abstract Seascapes by Ritushka",
    "seoTitle": "Abstract Seascapes | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore abstract seascapes by Ritushka — original abstract seascape paintings for buyers of coastal and ocean abstract art. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's abstract seascapes — original abstract seascape paintings created for buyers of coastal and ocean abstract art. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 60 × 60 cm to 150 × 100 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these abstract seascapes come in?",
        "a": "This collection ranges from 60 × 60 cm to 150 × 100 cm — Coastal Waters is the most intimate and One of a Kind the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 13 works available in this collection."
      },
      {
        "q": "How much do abstract seascapes cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-03",
    "slug": "large-scale-paintings",
    "name": "Large Scale Paintings",
    "keyword": "large scale art",
    "intent": "designers and architects sourcing expansive statement works",
    "heading": "Large Scale Paintings by Ritushka",
    "seoTitle": "Large Scale Paintings | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore large scale paintings by Ritushka — original large scale art for designers and architects sourcing expansive statement works. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's large scale paintings — original large scale art created for designers and architects sourcing expansive statement works. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 79 × 138 cm to 100 × 150 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these large scale paintings come in?",
        "a": "This collection ranges from 79 × 138 cm to 100 × 150 cm — Horizon is the most intimate and Plateau the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 4 works available in this collection."
      },
      {
        "q": "How much do large scale paintings cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-04",
    "slug": "coastal-abstract-art",
    "name": "Coastal Abstract Art",
    "keyword": "coastal abstract art",
    "intent": "luxury coastal homes",
    "heading": "Coastal Abstract Art by Ritushka",
    "seoTitle": "Coastal Abstract Art | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore coastal abstract art by Ritushka — original coastal abstract art for luxury coastal homes. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's coastal abstract art — original coastal abstract art created for luxury coastal homes. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 60 × 60 cm to 150 × 100 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these coastal abstract art come in?",
        "a": "This collection ranges from 60 × 60 cm to 150 × 100 cm — Coastal Waters is the most intimate and One of a Kind the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 5 works available in this collection."
      },
      {
        "q": "How much do coastal abstract art cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-05",
    "slug": "ocean-inspired-paintings",
    "name": "Ocean Inspired Paintings",
    "keyword": "ocean inspired paintings",
    "intent": "collectors drawn to the sea",
    "heading": "Ocean Inspired Paintings by Ritushka",
    "seoTitle": "Ocean Inspired Paintings | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore ocean inspired paintings by Ritushka — original ocean inspired paintings for collectors drawn to the sea. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's ocean inspired paintings — original ocean inspired paintings created for collectors drawn to the sea. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 60 × 60 cm to 150 × 100 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these ocean inspired paintings come in?",
        "a": "This collection ranges from 60 × 60 cm to 150 × 100 cm — Coastal Waters is the most intimate and One of a Kind the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 10 works available in this collection."
      },
      {
        "q": "How much do ocean inspired paintings cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-06",
    "slug": "contemporary-landscape-art",
    "name": "Contemporary Landscape Art",
    "keyword": "contemporary landscape art",
    "intent": "modern interiors",
    "heading": "Contemporary Landscape Art by Ritushka",
    "seoTitle": "Contemporary Landscape Art | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore contemporary landscape art by Ritushka — original contemporary landscape art for modern interiors. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's contemporary landscape art — original contemporary landscape art created for modern interiors. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 60 × 60 cm to 150 × 100 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these contemporary landscape art come in?",
        "a": "This collection ranges from 60 × 60 cm to 150 × 100 cm — Blue Mountains is the most intimate and Paragliding the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 6 works available in this collection."
      },
      {
        "q": "How much do contemporary landscape art cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-07",
    "slug": "textured-abstract-paintings",
    "name": "Textured Abstract Paintings",
    "keyword": "textured abstract paintings",
    "intent": "collectors who value materiality and surface",
    "heading": "Textured Abstract Paintings by Ritushka",
    "seoTitle": "Textured Abstract Paintings | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore textured abstract paintings by Ritushka — original textured abstract paintings for collectors who value materiality and surface. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's textured abstract paintings — original textured abstract paintings created for collectors who value materiality and surface. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 60 × 60 cm to 150 × 100 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these textured abstract paintings come in?",
        "a": "This collection ranges from 60 × 60 cm to 150 × 100 cm — Blue Mountains is the most intimate and Paragliding the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 6 works available in this collection."
      },
      {
        "q": "How much do textured abstract paintings cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-08",
    "slug": "blue-abstract-paintings",
    "name": "Blue Abstract Paintings",
    "keyword": "blue abstract paintings",
    "intent": "colour-led buyers",
    "heading": "Blue Abstract Paintings by Ritushka",
    "seoTitle": "Blue Abstract Paintings | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore blue abstract paintings by Ritushka — original blue abstract paintings for colour-led buyers. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's blue abstract paintings — original blue abstract paintings created for colour-led buyers. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 60 × 60 cm to 152 × 91 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these blue abstract paintings come in?",
        "a": "This collection ranges from 60 × 60 cm to 152 × 91 cm — Coastal Waters is the most intimate and Softly Loving Dreamscape the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 11 works available in this collection."
      },
      {
        "q": "How much do blue abstract paintings cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-09",
    "slug": "modern-australian-art",
    "name": "Modern Australian Art",
    "keyword": "modern australian art",
    "intent": "buyers seeking Australian provenance",
    "heading": "Modern Australian Art by Ritushka",
    "seoTitle": "Modern Australian Art | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore modern australian art by Ritushka — original modern australian art for buyers seeking Australian provenance. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's modern australian art — original modern australian art created for buyers seeking Australian provenance. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 60 × 60 cm to 91 × 122 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these modern australian art come in?",
        "a": "This collection ranges from 60 × 60 cm to 91 × 122 cm — Blue Mountains is the most intimate and Bush the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 4 works available in this collection."
      },
      {
        "q": "How much do modern australian art cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-10",
    "slug": "statement-artworks",
    "name": "Statement Artworks",
    "keyword": "statement artwork",
    "intent": "corporate and luxury commissions",
    "heading": "Statement Artworks by Ritushka",
    "seoTitle": "Statement Artworks | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore statement artworks by Ritushka — original statement artwork for corporate and luxury commissions. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's statement artworks — original statement artwork created for corporate and luxury commissions. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 60 × 60 cm to 100 × 120 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these statement artworks come in?",
        "a": "This collection ranges from 60 × 60 cm to 100 × 120 cm — Marshmallow is the most intimate and Strangely Attracted to You the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 8 works available in this collection."
      },
      {
        "q": "How much do statement artworks cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  },
  {
    "id": "col-11",
    "slug": "other-works",
    "name": "Other Works",
    "keyword": "original figurative and decorative art",
    "intent": "collectors looking beyond landscape",
    "heading": "Other Works by Ritushka",
    "seoTitle": "Other Works | Original Paintings by Ritushka, Sydney",
    "metaDescription": "Explore other works by Ritushka — original original figurative and decorative art for collectors looking beyond landscape. Contemporary artist in Lane Cove, Sydney, shipping worldwide. Enquire about available works and commissions.",
    "intro": "This collection brings together Ritushka's other works — original original figurative and decorative art created for collectors looking beyond landscape. Each work is painted in layers from a Lane Cove, Sydney studio and ships worldwide with a certificate of authenticity. Works in this collection range from 50 × 40 cm to 120 × 180 cm, and every painting page lists its exact dimensions, depth and framing. Price is available on application.",
    "faqs": [
      {
        "q": "What sizes do these other works come in?",
        "a": "This collection ranges from 50 × 40 cm to 120 × 180 cm — Numero Uno is the most intimate and Tree of Our Lives the largest. Exact height, width, depth and framing are listed on every artwork page, and each work is shown to scale in a room mockup. There are currently 2 works available in this collection."
      },
      {
        "q": "How much do other works cost?",
        "a": "Price is provided on application and depends on the size and complexity of the work. Enquire about any piece and you will receive current pricing, availability and shipping options."
      },
      {
        "q": "Can I commission a work in this style?",
        "a": "Yes. Ritushka accepts commissions and will work to your size, palette and space. Allow 4-8 weeks of studio time plus shipping."
      },
      {
        "q": "Do you ship internationally?",
        "a": "Yes — all originals ship worldwide, fully insured, with tracking and a certificate of authenticity."
      }
    ]
  }
];
